import type { CardDefinition } from "../types";
import { drawOne, spell, trap, unit } from "./helpers";

export const STARTER_CARDS: CardDefinition[] = [
  unit({
    id: "spark-scout",
    name: "Spark Scout",
    set: "starter",
    family: "starter",
    cost: 1,
    attack: 1,
    health: 2,
    text: "A cheap opener that helps contest the board early.",
    artLabel: "Scout",
    visualTheme: "spark"
  }),
  unit({
    id: "iron-guard",
    name: "Iron Guard",
    set: "starter",
    family: "starter",
    cost: 2,
    attack: 2,
    health: 3,
    text: "Guard. Solid early defender.",
    artLabel: "Guard",
    visualTheme: "iron",
    keywords: ["guard"]
  }),
  unit({
    id: "dusk-duelist",
    name: "Dusk Duelist",
    set: "starter",
    family: "starter",
    cost: 3,
    attack: 4,
    health: 2,
    text: "Hits hard, but trades easily.",
    artLabel: "Blade",
    visualTheme: "dusk"
  }),
  unit({
    id: "river-serpent",
    name: "River Serpent",
    set: "starter",
    family: "starter",
    cost: 4,
    attack: 4,
    health: 4,
    text: "A clean midgame threat.",
    artLabel: "Serpent",
    visualTheme: "river"
  }),
  unit({
    id: "storm-rider",
    name: "Storm Rider",
    set: "starter",
    family: "starter",
    cost: 5,
    attack: 5,
    health: 4,
    text: "A fast finisher that pressures open boards.",
    artLabel: "Storm",
    visualTheme: "storm"
  }),
  unit({
    id: "vine-lurker",
    name: "Vine Lurker",
    set: "starter",
    family: "starter",
    cost: 3,
    attack: 2,
    health: 4,
    text: "Sticky midgame body that holds the line well.",
    artLabel: "Vines",
    visualTheme: "vine"
  }),
  unit({
    id: "lunar-mage",
    name: "Lunar Mage",
    set: "starter",
    family: "starter",
    cost: 4,
    attack: 3,
    health: 5,
    text: "Ranged. A resilient caster that stabilizes the board.",
    artLabel: "Moon",
    visualTheme: "lunar",
    keywords: ["ranged"]
  }),
  unit({
    id: "dawn-courier",
    name: "Dawn Courier",
    set: "starter",
    family: "starter",
    cost: 2,
    attack: 2,
    health: 1,
    text: "Swift. Can attack the turn it is played.",
    artLabel: "Dawn",
    visualTheme: "spark",
    keywords: ["swift"]
  }),
  unit({
    id: "gale-falcon",
    name: "Gale Falcon",
    set: "starter",
    family: "starter",
    cost: 3,
    attack: 2,
    health: 2,
    text: "Flying. Can pressure heroes over grounded units.",
    artLabel: "Falcon",
    visualTheme: "storm",
    keywords: ["flying"]
  }),
  unit({
    id: "sky-drake",
    name: "Sky Drake",
    set: "starter",
    family: "starter",
    cost: 4,
    attack: 3,
    health: 3,
    text: "Flying. A clean evasive threat that grounded units cannot hit.",
    artLabel: "Drake",
    visualTheme: "storm",
    keywords: ["flying"]
  }),
  unit({
    id: "bronze-charger",
    name: "Bronze Charger",
    set: "starter",
    family: "starter",
    cost: 3,
    attack: 3,
    health: 2,
    text: "Swift. Pressures weak openings right away.",
    artLabel: "Charge",
    visualTheme: "iron",
    keywords: ["swift"]
  }),
  unit({
    id: "siege-golem",
    name: "Siege Golem",
    set: "starter",
    family: "starter",
    cost: 6,
    attack: 6,
    health: 6,
    text: "A slow finisher that dominates empty boards.",
    artLabel: "Golem",
    visualTheme: "stone"
  }),
  unit({
    id: "stone-warden",
    name: "Stone Warden",
    set: "starter",
    family: "starter",
    cost: 5,
    attack: 3,
    health: 7,
    text: "Guard. A heavy blocker that stalls the board.",
    artLabel: "Warden",
    visualTheme: "stone",
    keywords: ["guard"]
  }),
  unit({
    id: "watchtower-archer",
    name: "Watchtower Archer",
    set: "starter",
    family: "starter",
    cost: 3,
    attack: 2,
    health: 4,
    text: "Guard, Ranged. Gives every starter deck a clean anti-air body.",
    artLabel: "Tower",
    visualTheme: "iron",
    keywords: ["guard", "ranged"]
  }),
  unit({
    id: "grave-lantern",
    name: "Grave Lantern",
    set: "starter",
    family: "starter",
    cost: 2,
    attack: 1,
    health: 2,
    text: "On death: draw 1 card.",
    artLabel: "Lantern",
    visualTheme: "lunar",
    onDeathEffects: [drawOne]
  }),
  unit({
    id: "field-medic",
    name: "Field Medic",
    set: "starter",
    family: "starter",
    cost: 3,
    attack: 2,
    health: 3,
    text: "On play: heal your hero for 3.",
    artLabel: "Medic",
    visualTheme: "tactics",
    onPlayEffects: [{ kind: "heal-hero", amount: 3, target: "self" }]
  }),
  unit({
    id: "hushwing-apprentice",
    name: "Hushwing Apprentice",
    set: "starter",
    family: "starter",
    cost: 2,
    attack: 2,
    health: 1,
    text: "Stealth. Stays hidden from unit attacks until it strikes.",
    artLabel: "Veil",
    visualTheme: "dusk",
    keywords: ["stealth"]
  }),
  spell({
    id: "ember-shot",
    name: "Ember Shot",
    set: "starter",
    family: "starter",
    cost: 2,
    text: "Deal 3 damage to the enemy hero.",
    effects: [{ kind: "damage-hero", amount: 3, target: "enemy" }],
    artLabel: "Flame",
    visualTheme: "ember"
  }),
  spell({
    id: "tactical-insight",
    name: "Tactical Insight",
    set: "starter",
    family: "starter",
    cost: 2,
    text: "Draw 1 card and give your strongest unit +1/+1.",
    effects: [
      { kind: "draw", amount: 1, target: "self" },
      { kind: "buff-unit", selector: "highest-attack-ally", attack: 1, health: 1 }
    ],
    artLabel: "Plans",
    visualTheme: "tactics"
  }),
  spell({
    id: "flame-sweep",
    name: "Flame Sweep",
    set: "starter",
    family: "starter",
    cost: 4,
    text: "Deal 2 damage to all enemy units.",
    effects: [{ kind: "damage-units", amount: 2, side: "enemy" }],
    artLabel: "Sweep",
    visualTheme: "ember"
  }),
  spell({
    id: "spark-burst",
    name: "Spark Burst",
    set: "starter",
    family: "starter",
    cost: 1,
    text: "Deal 2 damage to the enemy hero.",
    effects: [{ kind: "damage-hero", amount: 2, target: "enemy" }],
    artLabel: "Burst",
    visualTheme: "spark"
  }),
  spell({
    id: "river-mist",
    name: "River Mist",
    set: "starter",
    family: "starter",
    cost: 3,
    text: "Draw 1 card and heal your hero for 2.",
    effects: [
      { kind: "draw", amount: 1, target: "self" },
      { kind: "heal-hero", amount: 2, target: "self" }
    ],
    artLabel: "Mist",
    visualTheme: "river"
  }),
  spell({
    id: "storm-surge",
    name: "Storm Surge",
    set: "starter",
    family: "starter",
    cost: 5,
    text: "Deal 3 damage to all enemy units.",
    effects: [{ kind: "damage-units", amount: 3, side: "enemy" }],
    artLabel: "Surge",
    visualTheme: "storm"
  }),
  spell({
    id: "rally-banner",
    name: "Rally Banner",
    set: "starter",
    family: "starter",
    cost: 3,
    text: "Give your strongest unit +2/+2.",
    effects: [{ kind: "buff-unit", selector: "highest-attack-ally", attack: 2, health: 2 }],
    artLabel: "Banner",
    visualTheme: "tactics"
  }),
  spell({
    id: "frost-tether",
    name: "Frost Tether",
    set: "starter",
    family: "starter",
    cost: 3,
    text: "Give the strongest enemy unit -2/-1.",
    effects: [{ kind: "debuff-unit", selector: "highest-attack-enemy", attack: 2, health: 1 }],
    artLabel: "Tether",
    visualTheme: "river"
  }),
  spell({
    id: "ration-cache",
    name: "Ration Cache",
    set: "starter",
    family: "starter",
    cost: 1,
    text: "Gain 2 resource this turn.",
    effects: [{ kind: "gain-resource", amount: 2, target: "self" }],
    artLabel: "Cache",
    visualTheme: "tactics"
  }),
  spell({
    id: "anchor-flip",
    name: "Anchor Flip",
    set: "starter",
    family: "starter",
    cost: 3,
    text: "Return the strongest enemy unit to its owner's hand.",
    effects: [{ kind: "bounce-unit", selector: "highest-attack-enemy" }],
    artLabel: "Anchor",
    visualTheme: "river"
  }),
  trap({
    id: "ambush-snare",
    name: "Ambush Snare",
    set: "starter",
    family: "starter",
    cost: 3,
    text: "When an enemy unit attacks, destroy that attacker and cancel the attack. Pricier now so early attacks are less punishing.",
    trigger: "enemy-attack",
    effect: { kind: "destroy-attacker", cancelAttack: true },
    artLabel: "Snare",
    visualTheme: "snare"
  }),
  trap({
    id: "spellwire",
    name: "Spellwire",
    set: "starter",
    family: "starter",
    cost: 2,
    text: "When your opponent casts a spell, deal 3 damage to that player.",
    trigger: "enemy-spell",
    effect: { kind: "damage-spell-owner", amount: 3 },
    artLabel: "Wire",
    visualTheme: "wire"
  }),
  trap({
    id: "mirror-rune",
    name: "Mirror Rune",
    set: "starter",
    family: "starter",
    cost: 1,
    text: "When your opponent casts a spell, draw 1 card.",
    trigger: "enemy-spell",
    effect: { kind: "triggered-effect", effect: { kind: "draw", amount: 1, target: "self" } },
    artLabel: "Rune",
    visualTheme: "lunar"
  }),
  trap({
    id: "bramble-pit",
    name: "Bramble Pit",
    set: "starter",
    family: "starter",
    cost: 3,
    text: "When an enemy unit attacks, cancel that attack and gain 2 resource this turn.",
    trigger: "enemy-attack",
    effect: { kind: "triggered-effect", effect: { kind: "gain-resource", amount: 2, target: "self" }, cancelAttack: true },
    artLabel: "Bramble",
    visualTheme: "vine"
  }),
  trap({
    id: "null-sigil",
    name: "Null Sigil",
    set: "starter",
    family: "starter",
    cost: 2,
    text: "When your opponent casts a spell, they pay 1 more or it is countered.",
    trigger: "enemy-spell",
    effect: { kind: "spell-tax", taxAmount: 1 },
    artLabel: "Sigil",
    visualTheme: "wire"
  })
];
