export type CampfireCardPack = {
  id: string;
  name: string;
  description: string;
  prompts: string[];
  answers: string[];
};

export const CAMPFIRE_CARD_PACKS: CampfireCardPack[] = [
  {
    "id": "retail-mini-pack",
    "name": "Retail Mini Pack",
    "description": "2 prompts, 3 responses from the imported CSV.",
    "prompts": [
      "How are the writers of Cards Against Humanity spending your $25?",
      "Looking to earn big bucks? Learn how to make ______ work for you!"
    ],
    "answers": [
      "A teenage boy gunning for a handjob.",
      "Feeding a man a pie made of his own children.",
      "Ironically buying a trucker hat and then ironically being a trucker for 38 years."
    ]
  },
  {
    "id": "90s-nostalgia-pack",
    "name": "90s Nostalgia Pack",
    "description": "9 prompts, 28 responses from the imported CSV.",
    "prompts": [
      "Believe it or not Jim Carrey can do a dead-on impression of ____.",
      "How did Stella get her groove back?",
      "I can show you ______, shining, shimmering, splendid.",
      "I'm a bitch, I'm a lover, I'm a child, I'm ______.",
      "If I were a Spice Girl, I’d be “______ Spice.”",
      "It's Morphin' Time! Mastodon! Pterodactyl! Triceratops! Sabertooth Tiger! ______!",
      "Siskel and Ebert have panned ______ as \"poorly conceived\" and \"sloppily executed.\"",
      "Tonight on SNICK: \"Are You Afriad of ______?",
      "Up next on Nickelodeon: \"Clarissa Explains ______.\""
    ],
    "answers": [
      "A bus that will explode if it goes under 50 miles per hour.",
      "A mulatto, an albino, a mosquito, and my libido.",
      "A threesome with 1996 Denise Richards and 1999 Denise Richards.",
      "Angels interfering in an otherwise fair baseball game.",
      "Cool 90s up-in-the-front hair.",
      "Deregulating the mortgage market.",
      "Freeing Willy.",
      "Getting caught up in the CROSSFIRE™.",
      "Getting jiggy with it, as it were.",
      "Jerking off to a 10-second RealMedia clip.",
      "Kurt Cobain's death.",
      "Letting Tim Allen do the Home Improvement grunt into my pussy.",
      "Liking big butts and not being able to lie about it.",
      "Log™.",
      "Painting with all the colors of the wind.",
      "Pamela Anderson's boobs running in slow motion.",
      "Patti Mayonnaise.",
      "Pizza in the morning, pizza in the evening, pizza at supper time.",
      "Pure Moods, Vol. 1.",
      "Several Michael Keatons",
      "Stabbing the shit out of a Capri Sun.",
      "Sucking the president's dick.",
      "Sunny D! Alright!",
      "The 1996 Chicago Bulls.",
      "The Great Cornholio.",
      "The Y2K bug.",
      "Wearing Nicolas Cage's face.",
      "Yelling \"girl power!\" and doing a high kick."
    ]
  },
  {
    "id": "geek-pack",
    "name": "Geek Pack",
    "description": "6 prompts, 30 responses from the imported CSV.",
    "prompts": [
      "______ is OP. Please nerf.",
      "______: Achievement unlocked. (Pax Prime 2013)",
      "(Heavy breathing) Luke, I am ______. (Pax East 2014)",
      "Press ↓ ↓ ← → B to unleash ______. (Pax East 2013 Promo Pack C)",
      "What made Spock cry? (Pax Prime 2013)",
      "What's the latest bullshit that's troubling this quaint fantasy town? (Pax Prime 2013)"
    ],
    "answers": [
      "A fully-dressed female videogame character. (Pax Prime 2013)",
      "A grumpy old Harrison Ford who'd rather be doing anything else. (Pax East 2014)",
      "A homemade, cum-stained Star Trek Uniform. (Pax Prime 2013)",
      "Achieving 500 actions per minute. (Pax East 2013 Promo Pack C)",
      "An unskippable cutscene.",
      "Charging up all the way. (Pax East 2013 Promo Pack C)",
      "Eating a pizza that's lying in the street to gain health. (Pax Prime 2013)",
      "Endless ninjas. (Pax East 2014)",
      "Forgetting to eat, and consequently dying. (Pax East 2013 Promo Pack C)",
      "Getting bitch slapped by Dhalsim. (Pax East 2013 Promo Pack A)",
      "Getting bitten by a radioactive spider and then battling leukimia for 30 years. (Pax East 2014)",
      "KHAAAAAAAAN! (Pax East 2014)",
      "Lag.",
      "Leroooooooooooy Jenkins!",
      "Loading from a previous save. (Pax East 2013 Promo Pack B)",
      "Microtransactions.",
      "My anime body pillow.",
      "Offering sexual favors for an ore and a sheep. (Pax Prime 2013)",
      "Running out of stamina. (Pax East 2013 Promo Pack A)",
      "Separate drinking fountains for dark elves. (Pax East 2014)",
      "Ser Jorah Mormont's cerulean-blue balls. (Pax East 2014)",
      "Sharpening a foam broadsword on a foam whetstone. (Pax East 2013 Promo Pack B)",
      "Stuffing my balls into a Sega Genesis and pressing the power button. (Pax East 2014)",
      "Taking 2d6 emotional damage. (Pax East 2014)",
      "Tapping Serra Angel. (Pax Prime 2013)",
      "The Cock Ring of Alacrity. (Pax Prime 2013)",
      "The collective wail of every Magic player suddenly realizing that they've spent hundreds of dollars on pieces of cardboard. (Pax Prime 2013)",
      "The depression that ensues after catching 'em all. (Pax East 2013 Promo Pack B)",
      "Waluigi.",
      "Yoshi's huge egg-laying cloaca. (Pax Prime 2013)"
    ]
  },
  {
    "id": "sci-fi-pack",
    "name": "Sci-Fi Pack",
    "description": "7 prompts, 27 responses from the imported CSV.",
    "prompts": [
      "Computer! Display ______ on screen. Enhance.",
      "Fear leads to anger. Anger leads to hate. Hate leads to ______.",
      "Madam President, the asteroid is headed directly for Earth and there's only one thing that can stop it: ______.",
      "This won't be like negotiating with the Vogons. Humans only respond to one thing: ______.",
      "What is the answer to life, the universe, and everything?",
      "You have violated the Prime Directive! You exposed an alien culture to ______ before they were ready.",
      "You're not going to believe this, but I'm you from the future! You've got to stop ______."
    ],
    "answers": [
      "[A picture of Sean Connery in the movie Zardoz]",
      "A hazmat suit full of farts.",
      "A misty room full of glistening egg sacs.",
      "A planet-devouring space worm named Rachel.",
      "A protagonist with no qualities.",
      "A supercomputer that predicts the future with 100% accuracy.",
      "An alternate history where Hitler was gay but he still killed all those people.",
      "Astronaut pussy.",
      "Beep beep boop beep boop.",
      "Cheerful blowjob robots.",
      "Cosmic bowling.",
      "Cumming into a black hole.",
      "Darmok and Jalad at Tanagra.",
      "Frantically writing equations on a chalkboard.",
      "Funkified aliens from the planet Groovius.",
      "Going too far with science and bad things happening.",
      "How great of a movie Men In Black was.",
      "Laying thousands of eggs in a man's colon.",
      "Masturbating Yoda's leathery turtle-penis.",
      "Nine seasons of sexual tension with David Duchovny.",
      "That girl from the Hunger Games.",
      "The dystopia we're living in right now.",
      "The ending of Lost.",
      "Three boobs.",
      "Transferring my consciousness into a guinea pig.",
      "Trimming the poop out of Chewbacca's butt hair.",
      "Vulcan sex-madness."
    ]
  },
  {
    "id": "movie-night-box",
    "name": "Movie Night Box",
    "description": "3 prompts, 27 responses from the imported CSV.",
    "prompts": [
      "And the Acadamy Award for Best Picture goes to... ______ Everywhere All At Once!",
      "Fans are up in arms after learning that the new \"Little Mermaid\" is ______.",
      "Coming to theaters, He Got ______: A Spike Lee Joint."
    ],
    "answers": [
      "James Cameron staring in the mirror and wondering why he's devoted thirty years of his life to blue-alien hentai.",
      "A movie where two hot people fall in love, but there's a problem.",
      "Having sex with all the cars from Cars.",
      "A Human Centipede-type scenario.",
      "Explosions, shouting, guns, breasts, etc.",
      "Getting slapped by Will Smith.",
      "A sudden jump cut to Ed Harris fucking a swan.",
      "An all-female reboot of The Godfather.",
      "Dave Bautista's huge, muscular neck.",
      "Getting my balls smashed in a film clapboard.",
      "Quentin Tarantino's foot fetish.",
      "Some kind of psychosexual David Lynch situation.",
      "The Muppet adaptation of Schindler's List.",
      "The movie White Chicks.",
      "Marty McFly's horny mom.",
      "Dispensing hot popcorn butter all over my tight little asshole.",
      "Diverse casting decisions.",
      "Jumanji.",
      "Whacking off to the diarrhea scene in Bridesmaids.",
      "Shamelessly pandering to the lowest common denominator.",
      "A bunch of crazy anime shit.",
      "A Batman movie where Batman gets bitten by a radioactive snake, which turns him into Snake Batman, and he slithers around Gotham swallowing criminals.",
      "A whole lot of Jews.",
      "Laura Dern.",
      "Subtext.",
      "Accidentally spilling John Wick's coffee.",
      "I am Groot I am Groot I am Groot ARE YOU LAUGHING YET? I am Groot I am Groot I am Groot ISN'T IT FUNNY? I am Groot I am Groot I am Groot HAHAHA IT'S SO FUCKING FUNNY THAT'S ALL HE CAN SAY, GOD I LOVE MARVEL."
    ]
  },
  {
    "id": "fantasy-pack",
    "name": "Fantasy Pack",
    "description": "5 prompts, 29 responses from the imported CSV.",
    "prompts": [
      "And in the end, the dragon was not evil; he just wanted ______.",
      "Having tired of poetry and music, the immortal elves now fill their days with ______.",
      "Legend tells of a princess who has been asleep for a thousand years and can only be awoken by ______.",
      "Who blasphemes and bubbles at the center of all infinity, whose name no lips dare speak aloud, and who gnaws hungrily in inconceivable, unlighted chambers beyond time?",
      "Your father was a powerful wizard, Harry. Before he died, he left you something very precious: ___."
    ],
    "answers": [
      "A CGI dragon.",
      "A dwarf who won't leave you alone until you compare penis sizes.",
      "A gay sorcerer who turns everyone gay.",
      "A ghoul.",
      "A gnome who won’t leave you alone until you compare penis sizes.",
      "A Hitachi Magic Wand.",
      "A hot swamp full of horny witches.",
      "A magical kingdom with dragons and elves and no black people.",
      "A mysterious, floating orb.",
      "A weed elemental who gets everyone high.",
      "Accidentally conjuring a legless horse that can't stop ejaculating.",
      "Astral-projecting into the Goat Realm.",
      "Bathing naked in a moonlit grove.",
      "Dinosaurs who wear armor and you ride them and they kick ass.",
      "Eternal darkness.",
      "Foraging for berries in yonder wood.",
      "Freaky, pan-dimensional sex with a demigod.",
      "Gender equality.",
      "Going on an epic adventure and learning a valuable lesson about friendship.",
      "Handcuffing a wizard to a radiator and dousing him with kerosene.",
      "Hodor.",
      "How hot Orlando Bloom was in Lord of the Rings.",
      "Kneeing a wizard in the balls.",
      "Make-believe stories for autistic white men.",
      "Reading The Hobbit under the covers while mom and dad scream at each other downstairs.",
      "Shitting in a wizard's spell book and jizzing in his hat.",
      "Shooting a wizard with a gun.",
      "The all-seeing Eye of Sauron.",
      "The bond of brotherhood forged in battle, unbreakable and eternal."
    ]
  },
  {
    "id": "world-wide-web-pack",
    "name": "World Wide Web Pack",
    "description": "7 prompts, 26 responses from the imported CSV.",
    "prompts": [
      "Don't worry, Penny! Go Go Gadget ______!",
      "I'm just gonna stay in tonight. You know, Netflix and ______.",
      "Nothing says \"I love you\" like ______.",
      "This app is basically Tinder, but for ______.",
      "TRIGGER WARNING: ______.",
      "What did I nickname my genitals?",
      "You guys, you can buy ______ on the dark web."
    ],
    "answers": [
      "A complete inability to understand anyone else's perspective.",
      "A fun, sexy time at the nude beach.",
      "A man from Craigslist.",
      "A night of Taco Bell and anal sex.",
      "A respectful discussion of race and gender on the Internet.",
      "Cat massage.",
      "Destroying Dick Cheney's last horcrux.",
      "Game of Thrones spoilers.",
      "Getting death threats.",
      "Getting teabagged by a fifth grader in Call of Duty.",
      "Goats screaming like people.",
      "Googling.",
      "Internet porn analysis paralysis.",
      "Lofi hip hop beats to relax/study to.",
      "Matching with Mom on Tinder.",
      "My browser history.",
      "My privileged white penis.",
      "Pretending to be black.",
      "Smash Mouth.",
      "Some racist-ass shit.",
      "Taking a shit while running at full speed.",
      "That thing on the Internet everyone's talking about.",
      "Three years of semen in a shoebox.",
      "Tweeting an apology.",
      "W. W. W. DOT BIG DADDY SEX HOLE DOT COM.",
      "Youtube comments."
    ]
  },
  {
    "id": "science-pack",
    "name": "Science Pack",
    "description": "4 prompts, 23 responses from the imported CSV.",
    "prompts": [
      "A study published in Nature this week found that ______ is good for you in small doses.",
      "Hey there, Young Scientists! Put on your labcoats and strap on your safety goggles, because today we're learning about ______!",
      "In what's being hailed as a major breakthrough, scientists have synthesized ______ in the lab.",
      "What really killed the dinosaurs?"
    ],
    "answers": [
      "3.7 billion years of evolution.",
      "A 0.7 waist-to-hip ratio.",
      "A supermassive black hole.",
      "Achieving reproductive success.",
      "Being knowledgeable in a narrow domain that nobody understands or cares about.",
      "David Attenborough watching us mate.",
      "Developing secondary sex characteristics.",
      "Driving into a tornado to learn about tornadoes.",
      "Electroejaculating a capuchin monkey.",
      "Evolving a labyrinthine vagina.",
      "Explosive decompression.",
      "Failing the Turing test.",
      "Fun and interesting facts about rocks.",
      "Getting really worried about global warming for a few seconds.",
      "Infinity.",
      "Insufficient serotonin.",
      "Oxytocin release via manual stimulation of the nipples.",
      "Photosynthesis.",
      "Reconciling quantum theory with general relativity.",
      "Slowly evaporating.",
      "The quiet majesty of the sea turtle.",
      "The Sun engulfing the Earth.",
      "Uranus."
    ]
  },
  {
    "id": "food-pack",
    "name": "Food Pack",
    "description": "7 prompts, 26 responses from the imported CSV.",
    "prompts": [
      "Aw babe, your burbs smell like ______.",
      "Don’t miss Rachel Ray’s hit new show, Cooking with ______.",
      "Don't miss Rachael Ray's hit new show, Cooking with ______.",
      "Excuse me, waiter. Could you take this back? This soup tastes like ______.",
      "I’m Bobby Flay, and if you can’t stand ______. get out of the kitchen!",
      "It’s not delivery. It’s ______.",
      "Now on Netflix: Jiro Dreams Of ______."
    ],
    "answers": [
      "A belly full of hard-boiled eggs.",
      "A joyless vegan patty.",
      "A sobering quantity of chili cheese fries.",
      "A table for one at The Cheesecake Factory.",
      "Being emotionally and physically dominated by Gordon Ramsay.",
      "Clamping down on a gazelle’s jugular and tasting its warm life waters.",
      "Committing suicide at the Old Country Buffet.",
      "Father’s forbidden chocolates.",
      "Going vegetarian and feeling so great all the time.",
      "Jizz Twinkies.",
      "Kale farts.",
      "Kevin Bacon Bits.",
      "Licking the cake batter off of grandma’s fingers.",
      "Motherfucking tater tots.",
      "Not knowing what to believe anymore about butter.",
      "Oreos for dinner.",
      "Real cheese flavor.",
      "Soup that’s better than pussy.",
      "Sucking down thousands of pounds of krill every day.",
      "Swishing the wine around and sniffing it like a big fancy man.",
      "The $1 Beefy Fritos Burrito from Taco Bell.",
      "The Dial-A-Slice Apple Divider from Williams-Sonoma.",
      "The Hellman’s Mayonnaise Corporation.",
      "The hot dog I put in my vagina ten days ago.",
      "The inaudible screams of carrots.",
      "What to do with all of this chocolate on my penis."
    ]
  },
  {
    "id": "cards-of-humor-and-whimsy-original-1923-edition",
    "name": "Cards of Humor and Whimsy: Original 1923 Edition",
    "description": "0 prompts, 30 responses from the imported CSV.",
    "prompts": [],
    "answers": [
      "A bit of whiskey for the baby.",
      "A fella whose tallywhacker bends 'round like a trombone!",
      "A horse riding another horse!",
      "A variety of jellies and marmalades.",
      "A woman politician?!",
      "Amateur taxidermy,",
      "Assassinating Archduke Franz Ferdinand.",
      "Bathtub gin.",
      "Bees!",
      "Bolshevik rabble-rousers.",
      "Catching and eating a leprechaun.",
      "Dying on the Titanic.",
      "Having a gay old time.",
      "Indecorous references to the girth of President Taft.",
      "Loose women.",
      "My six ugly sons.",
      "Passing gas and scampering away!",
      "Sexual cannibalism.",
      "Shucking corn with the fellas.",
      "Spending four days in an opium haze.",
      "The Boston Molasses Disaster.",
      "The feeling you get when an Italian buys the house next to you.",
      "The grandest adventure of all: life.",
      "The milk of my loins.",
      "The refreshing zing of Coca-Cola, with real cocaine!",
      "The Science of Eugenics.",
      "These healthy, delicious Lucky Strike cigarettes!",
      "Trout!",
      "Using my penis as a metronome.",
      "Woodrow Wilson's red-hot pecker!"
    ]
  },
  {
    "id": "pussy-pack",
    "name": "Pussy Pack",
    "description": "1 prompts, 2 responses from the imported CSV.",
    "prompts": [
      "______? Bap!"
    ],
    "answers": [
      "[picture of Noelle's butt]",
      "[picture of an angry hariless cat]"
    ]
  },
  {
    "id": "period-pack",
    "name": "Period Pack",
    "description": "6 prompts, 21 responses from the imported CSV.",
    "prompts": [
      "Can a woman really have it all? A career and ______?",
      "My body, my voice! ______, my choice!",
      "My vagina's angry. My vagina's furious and needs to talk. It needs to talk about ______.",
      "New fom Mattel, it's ______ Barbie!",
      "Tampax: Don’t let your period ruin ______.",
      "What gets me wet?"
    ],
    "answers": [
      "A diverse group of female friends casually discussing the side effects of birth control.",
      "A woman president.",
      "Always© Infinity Extra Heavy Overnight Pads with Wings.",
      "An emotionally draining friendship.",
      "Carrying a fetus to term.",
      "Catching a whiff of my vag.",
      "Dancing carefree in white linen pants.",
      "Destroying a pair of underwear.",
      "Drinking Beyoncé's DivaCup and becoming immortal.",
      "Driving my daughter to her abortion.",
      "Eating three sleeves of Chips Ahoy!",
      "Feeling bloaty and crampy.",
      "Feeling lots of feelings.",
      "Full bush.",
      "How bloody that dick's about to be.",
      "Masturbating with a Sonicare.",
      "Period globs.",
      "Playing with my pussy while I watch TV.",
      "Post-partum depression.",
      "Pulling out a never-ending tampon.",
      "Pussy lips of all shapes and sizes."
    ]
  },
  {
    "id": "weed-pack",
    "name": "Weed Pack",
    "description": "4 prompts, 22 responses from the imported CSV.",
    "prompts": [
      "Everyone is staring at you because you're ___.",
      "Hold up. I gotta deal with ___, then l'mma smoke this.",
      "Instead of playing a card this round, everyone must stare the Card Czar while making a sound you'd make after tasting something delicious.",
      "Okay here's the pitch. James Franco and Seth Rogen are trying to score some weed, and then ___ happens."
    ],
    "answers": [
      "A bong rip so massive it restores justice to the kingdom.",
      "A sandwich with Cheetos in it!",
      "A whole cheese pizza just for me.",
      "An eight-foot man smoking a six-foot bong.",
      "Ancient aliens.",
      "Being too high for airplane.",
      "Cheese crunchies.",
      "Dank ass cancer weed.",
      "Dicking around on the guitar for an hour.",
      "Dropping stuff and knocking everything over.",
      "Eating all the skin off a rotisserie chicken.",
      "Forgetting to breathe and then dying.",
      "Getting high and watching Planet Earth.",
      "Grinning like an idiot.",
      "Hot tub.",
      "How bright the sun is.",
      "Huge popcorn nugs of hairy alien weed.",
      "My own fingers.",
      "Smoking a blunt butt-ass naked.",
      "Smoking a joint with former President Barack Obama.",
      "Snoop Dogg.",
      "The banks, the media, the entire system, man."
    ]
  },
  {
    "id": "blackbox-press-kit",
    "name": "Blackbox Press Kit",
    "description": "0 prompts, 1 responses from the imported CSV.",
    "prompts": [],
    "answers": [
      "Lighting a circle of black candles and trying every flavor of Doritos®."
    ]
  },
  {
    "id": "design-pack",
    "name": "Design Pack",
    "description": "0 prompts, 28 responses from the imported CSV.",
    "prompts": [],
    "answers": [
      "formatted like 2 of hearts playing card",
      "clay figures having sex on a couch",
      "a woman peeing on man in public several centuries ago as her friend laughs",
      "light brown word on brown background",
      "letters/numbers printed in white rows on red background",
      "blue words on cartoon of chicken giving man blowjob",
      "word handwritten in cursive underneath picture of q-tip covered in red substance",
      "word labeled on what looks like a middle eastern candy label design, featuring a chicken enjoying a lollipop",
      "white word on pink background with white curlique designs behind it",
      "colored letters on white background in square formation",
      "In word bubble yelled by a leg wearing green tights in pink/red face with white background",
      "dripping colorful letters on black background with the letters at different heights",
      "pink letters on white background",
      "Fancy black curlique script on white background",
      "Colored letters on black background",
      "words around black and white bearded man drawing",
      "Letters arranged in square around yellowish gradient",
      "cursive word in brown on yellow background with the two 's's being eyes for a smiley face",
      "white word on yellow backdrop with white droplet outline around it",
      "18-in-1 Hemp PEPPERMINT', George Carlin quote",
      "word on top of 'The Crystal Goblet, of Printing Should be Invisible' by Beatrice Warde (1930)",
      "word on sign sticking out from cartoon skull",
      "formatted as a Tweet",
      "word on picture of space featuring the death star (?)",
      "Word printed above very old picture of nude woman covering herself",
      "formatted sort of like half nude queen of hearts playing card",
      "drawing of sagging boobs with the nipples forming the word's 'T's)",
      "word above typed printed out of: (@) (@)"
    ]
  },
  {
    "id": "theatre-pack",
    "name": "Theatre Pack",
    "description": "2 prompts, 0 responses from the imported CSV.",
    "prompts": [
      "Alright everybody, HOLD! Kelly, why is there ______ on my stage?",
      "Comedy = Tragedy + ______."
    ],
    "answers": []
  },
  {
    "id": "college-pack",
    "name": "College Pack",
    "description": "6 prompts, 23 responses from the imported CSV.",
    "prompts": [
      "All classes today are cancelled due to ______.",
      "Did you know? Our college was recently named the #1 school for ______!",
      "In this paper, I will explore ______ from a feminist perspective.",
      "My memory of last night is pretty hazy. I remember ______ and that's pretty much it.",
      "Pledges! Time to prove you're Delta Phi material. Chug this beer, take off your shirts, and get ready for ______.",
      "The Department of Psychology is looking for paid research volunteers. Are you 18-25 and suffering from ______."
    ],
    "answers": [
      "A 30-rack of Natty Light.",
      "A bachelor's degeree in communications.",
      "A girl who is so interesting that she has blue hair.",
      "A Yale man.",
      "An emergency all-floor meeting on inclusion.",
      "Boycotting Israel.",
      "Calling mom because it's just really hard and I miss her and I don't know anyone here.",
      "Falling in love with poetry.",
      "Five morons signing a lease together.",
      "Fucking the beat boxer from the a cappella group.",
      "Going to college and becoming a new person, who has sex.",
      "Googling how to eat pussy.",
      "Horny Christian Teens.",
      "How many Asians there are.",
      "My high school boyfriend.",
      "Performative wokeness.",
      "Pretending to have done the reading.",
      "Rocking a 1.5 GPA.",
      "Sucking a flaccid penis for 20 minutes.",
      "The sound of my roommate masturbating.",
      "Throw up.",
      "Uggs, leggings, and a North Face.",
      "Underage drinking."
    ]
  },
  {
    "id": "saves-america",
    "name": "Saves America",
    "description": "7 prompts, 22 responses from the imported CSV.",
    "prompts": [
      "\"They’re bringing drugs. They’re bringing crime. They’re rapists. And some, I assume, are _____.\"",
      "Cry havoc and let slip ______!",
      "Now is the winter of our discontent, made glorious summer by ______.",
      "The fault, dear Brutus, is not in our stars, but in ______.",
      "We want a pitcher, not ______!",
      "When asked about the biggest threat facing the nation, 60% of Americans said ______.",
      "You see, son, baseball is like ______. Don't overthink it."
    ],
    "answers": [
      "A baby panda that just can't keep its eyes open.",
      "A gay Republican somehow.",
      "A laundry basket full of baby bunnies.",
      "A really good dog.",
      "A stack of puppies in a trench coat.",
      "Getting deported.",
      "Guacamole.",
      "How easy it is to climb over a wall with a ladder.",
      "Lou Gehrig's Disease.",
      "Mexicans and Muslims.",
      "My drunk father screaming from the bleachers.",
      "Our dumb asshole president.",
      "Slowly shaking my head at a sad statistic.",
      "Speaking in iambic pentameter.",
      "Taking a minute to really unpack what Shakespeare is getting at in this scene.",
      "Teaching my son to love the Red Sox and hate minorities.",
      "The shocking stupidity of the American public.",
      "The significance of eyes in King Lear.",
      "The truth.",
      "Two baby otters holding hands.",
      "Two hamsters nibbling on a tiny burrito.",
      "White people becoming a minority."
    ]
  },
  {
    "id": "dad-pack-dvd-cover-s",
    "name": "Dad Pack/DVD Cover(s)",
    "description": "6 prompts, 21 responses from the imported CSV.",
    "prompts": [
      "Coming up on Turner Classic Movies: Sean Connery and Alec Baldwin star in \"The Hunt for ______.\"",
      "FW: re: FBI WARNING!!! VIOLENT GANGS USING ______ TO RECRUIT CHILDREN!",
      "Hey, kids. I'm Connor's dad, but you can call me Mr. ______.",
      "So apparently Dad was searching Pornhub for \"hot milf ______.\"",
      "Whaddya think, money grows on trees? I'm not paying for ______!",
      "Young lady, you better knock it off with ______ or you're grounded!"
    ],
    "answers": [
      "A positive male role model.",
      "Coaching the 7th grade girls basketball team.",
      "Dad coming home drunk.",
      "Dad's big sex night.",
      "Dad's famous chili.",
      "Divorce.",
      "Dolby® Digital Surround Sound.",
      "Emotional unavailability.",
      "Finding a place to sit down.",
      "Flirting with the ladies at the bank.",
      "Forty-two years of repressed homosexuality.",
      "Going bald.",
      "Having a bunch of kids by accident.",
      "Having a heart attack.",
      "Kidnapping Liam Neeson's daughter.",
      "Low sperm motility.",
      "Making the printer work.",
      "Mulch.",
      "My tired husband's soft penis.",
      "Puns.",
      "Sitting on the toilet for 45 minutes."
    ]
  },
  {
    "id": "pride-pack",
    "name": "Pride Pack",
    "description": "5 prompts, 24 responses from the imported CSV.",
    "prompts": [
      "Excuse me, straight man, but ______ isn't for you, STRAIGHT MAN.",
      "GOD HATES ______!",
      "If you can't love yourself, how the hell you gonna love ______?",
      "We're here! We're ______! Get used to it!",
      "YAAAAAAS! You are serving me ______ realness!"
    ],
    "answers": [
      "30 shirtless bears emerging from the fog.",
      "A 6-hour conversation on gender and queer theory.",
      "A big black dick strapped to a frail white body.",
      "A genderless hole.",
      "A messy bitch who lives for drama.",
      "A Subaru.",
      "A twink in a bounce house.",
      "All the different kinds of lesbians.",
      "Black, white, Puerto Rican, and Chinese boys.",
      "Britney, bitch!",
      "Getting your ass ate.",
      "Having your titties sucked while sucking on titties.",
      "Licking that pussy right.",
      "Marsha P. Johnson, the trans woman of color who may have thrown the first brick at Stonewall.",
      "Older fitness gays.",
      "Peeing in a bathroom.",
      "Poppers and lube.",
      "PrEP.",
      "Repeatedly coming out as bisexual.",
      "Talking, laughing, loving, breathing, fighting, fucking, crying, drinking, riding, winning, losing, cheating, kissing, thinking, dreaming.",
      "Telling Heather she can't pull off that top.",
      "The careless cunt who left a water ring on my credenza.",
      "The pan-ethnic, gender-fluid children of the future.",
      "Those cheekbones, honey."
    ]
  },
  {
    "id": "clickhole-greeting-cards-pack-target-exclusive",
    "name": "ClickHole Greeting Cards Pack (Target Exclusive)",
    "description": "4 prompts, 0 responses from the imported CSV.",
    "prompts": [
      "Hallmark has invented a new holiday. It's called \"________________ Day.\"",
      "Happy Birthday! I love you. Here's ________________.",
      "Honey, it's gonna take more than a shitty greeting card to make up for ten years of ________________.",
      "I cannot stop smiling about ________________."
    ],
    "answers": []
  },
  {
    "id": "ass-pack",
    "name": "Ass Pack",
    "description": "3 prompts, 8 responses from the imported CSV.",
    "prompts": [
      "I like ______ and I cannot lie!",
      "My anaconda don't want none unless you got ________, hun.",
      "My homeboys tried to warn me, but _______ makes me so horny."
    ],
    "answers": [
      "An ass like two football helmets.",
      "An ass like two old Italian faces telling secrets.",
      "Bad bitches with fat asses.",
      "Being grossly unprepared for this jelly.",
      "Blowing a fart hole in my yoga pants.",
      "Carrying my poop around in a ziplock bag.",
      "Cellulite.",
      "Cheesy French anus."
    ]
  },
  {
    "id": "2000s-nostalgia-pack",
    "name": "2000s Nostalgia Pack",
    "description": "5 prompts, 6 responses from the imported CSV.",
    "prompts": [
      "______? That's a no from me, dawg.",
      "16 people. 39 days of ______. One Survivor.",
      "I couldn't help but wonder. Was \"having it all\" an unattainable myth? Was the secret to a truly happy life just ______?",
      "Oh my god! ______ killed Kenny!",
      "Oops! I did it again. I played with ______."
    ],
    "answers": [
      "All these boys in my yard asking for milkshakes.",
      "Being a total Miranda.",
      "Blowing Lucas on an inflatable chair.",
      "Chunky highlights.",
      "Collateralized debt obligations.",
      "Competing against 20 other women for the love of Flava Flav."
    ]
  },
  {
    "id": "hidden-gems-bundle-a-few-new-cards-we-crammed-into-t",
    "name": "Hidden Gems Bundle: A Few New Cards We Crammed Into This Bundle Pack (Amazon Exclusive)",
    "description": "2 prompts, 7 responses from the imported CSV.",
    "prompts": [
      "HELP WANTED: Need assistance with ______. No experience necessary.",
      "Oh, whoops! These are not the right pants for ______."
    ],
    "answers": [
      "A juicy lil' booty going poot-poot-pooty.",
      "Abort-tron, the abortion robot.",
      "Dumping Mountain Dew Baja Blas all over my gorgeous natural titties.",
      "Getting radicalized on YouTube.",
      "Getting spit on by one hundred women.",
      "Sitting atop a pile of tuna like some kind of tuna queen.",
      "Watching the show \"Frasier\" and feeling the emotion \"pleasure.\""
    ]
  },
  {
    "id": "nerd-bundle-a-few-more-cards-for-you-nerds-target-ex",
    "name": "Nerd Bundle: A Few More Cards For You Nerds (Target Exclusive)",
    "description": "1 prompts, 9 responses from the imported CSV.",
    "prompts": [
      "Did not enjoy ______. One star."
    ],
    "answers": [
      "A hit new fantasy show called \"Penis Man.\"",
      "A magnificent chrome sphere that roams the streets evaporating criminals.",
      "Eating up whatever slop Marvel throws out there.",
      "Hot dog, the game you can eat, but only once.",
      "Not exercising.",
      "Running afoul of the sultan's Janissaries.",
      "Scrimshaw, the art of bone carving.",
      "The illusion of linear time.",
      "The last season of Game of Thrones."
    ]
  },
  {
    "id": "pop-culture-bundle-a-few-extra-cards-about-pop-cultu",
    "name": "Pop Culture Bundle - A Few Extra Cards About Pop Culture",
    "description": "2 prompts, 8 responses from the imported CSV.",
    "prompts": [
      "New from Marie Kondo: \"The Life-Changing Magic of _______.\"",
      "TMZ Exclusive: Pete Davidson taking a break from comedy to focus on _______."
    ],
    "answers": [
      "A centaur that's half camel, half Ellen DeGeneres.",
      "A threesome with the Property Brothers.",
      "Accidentally saying Shrek's name during sex.",
      "Dead Queen Elizabeth II.",
      "Getting shot by Alec Baldwin.",
      "How big Liam Neeson's dick probably is.",
      "Jeremy Renner getting run over by his own snow plow like a fucking idiot.",
      "Will Smith."
    ]
  },
  {
    "id": "nasty-bundle-a-few-extra-nasty-cards-for-you-people",
    "name": "Nasty Bundle: A Few Extra Nasty Cards For You People",
    "description": "5 prompts, 0 responses from the imported CSV.",
    "prompts": [
      "A toilet that begs for your shit.",
      "Barfing cum.",
      "Coating an Alpine ibex's ballsack with tamarind sauce.",
      "Deepthroating a man's foot.",
      "Gettina a cream-stain on your fuck-pants."
    ],
    "answers": []
  },
  {
    "id": "a-i-pack",
    "name": "A.I. Pack",
    "description": "0 prompts, 30 responses from the imported CSV.",
    "prompts": [],
    "answers": [
      "A killer’s diet of bush, cucumbers, and feathers.",
      "A woman who is so smart that she can predict the movements of 300 birds.",
      "Finding a nipple and being like “Oooh! That’s a nipple!”",
      "Getting Masturbated to.",
      "Giving grandma crappy things she doesn’t like.",
      "Ham finger.",
      "Hands down the best eggnog I have ever had.",
      "Insane empanadas.",
      "Kim Kardashian, but with spider legs.",
      "Laughing hysterically while my partner pours coffee into my eyes.",
      "More olives than you could possibly understand.",
      "Mr. Poop.",
      "My disgusting pot-bellied boy.",
      "P.F. Chang’s fusion of casual and formal cuisine.",
      "Screaming “there’s a hawk up my ass!”",
      "Secret CIA moon prisons.",
      "Sitting in the back of the plane, smoking a cigar and reading the Flickr privacy policy.",
      "Some kind of mutated shrimp that can suck dick like a pro.",
      "Some sort of unstoppable poo gun.",
      "Stairs.",
      "That shitty season of Mad Men where Sterling Cooper Draper Pryce gets destroyed by Daenerys Targaryen’s dragons.",
      "The amount of emotions a peanut would be capable of holding.",
      "The idea of a walrus.",
      "The lesbians of Iowa.",
      "The real story behind the yogurt that came out of Tina’s vagina.",
      "The unspeakable secrets of the weasels.",
      "These amazing testicles I’m about to share with you.",
      "These awesome gadgets that track my every move.",
      "These new jeans that look so cool but are actually so bad.",
      "What I Doin’."
    ]
  },
  {
    "id": "human-pack",
    "name": "Human Pack",
    "description": "2 prompts, 28 responses from the imported CSV.",
    "prompts": [
      "Do not go gentle into that good night. Rage, rage against ______?",
      "Sure, sex is great, but have you tried _______?"
    ],
    "answers": [
      "A pointless job at a soulless corporation.",
      "Being terrified of a single bee.",
      "Being young and in love in New York City.",
      "Chemotherapy.",
      "Delighting in the pain of others.",
      "Forming a monogamous pairbond.",
      "Getting my butt trapped hilariously in a tuba.",
      "Getting sad for no reason.",
      "Good ol’ fashioned face-to-face conversation.",
      "Harnessing the power of steam!!!",
      "How good this cantaloupe feels on my penis.",
      "Just hangin’ out, ya know?",
      "Like 50 mosquito bites.",
      "Losing a loved one to Fox News.",
      "Really tall people.",
      "Saying “what’s that?” And then stealing a french fry.",
      "Sucking all the oil out of the planet and fucking off to Mars.",
      "The bomb strapped to my chest.",
      "The joy of song.",
      "The salmon.",
      "The unspeakable horrors of factory farming.",
      "The whole Jeffrey Epstein thing.",
      "This horrible thing called twitter.",
      "Three hours of pimple-popping videos.",
      "Unwelcome sexual attention from grown men.",
      "Using words to communicate.",
      "War with China.",
      "Watching the life drain from the eyes of my son’s killer."
    ]
  },
  {
    "id": "picture-card-pack-1",
    "name": "Picture Card Pack 1",
    "description": "12 prompts, 18 responses from the imported CSV.",
    "prompts": [
      "Am I… ______?",
      "Enough. I tire of ______.",
      "Great job, Casey! Everybody loved ______.",
      "One day, this little girl will be ______.",
      "Take it from me, toots. I do not recommend ______.",
      "The ULTIMATE experience: ______ in VR.",
      "Tonight is the night. The night of ______.",
      "Uuuooooohhhhh, did you just say \"______?!\"",
      "What are they laughing at?",
      "What are they singing about?",
      "What is he thinking about?",
      "You're a tiger! You're crawling through the jungle. Now you're ______! Beautiful."
    ],
    "answers": [
      "[chimpanzee squatting]",
      "[Ronald McDonald]",
      "A compass that always points towards Robert De Niro's penis.",
      "AIR GUITARRRRR, WAHHHH!",
      "Amazon Prime.",
      "Getting fingered behind this dumpster.",
      "Having just masturbated.",
      "Heaven.",
      "Jerry the Jizzer and his stinky pogo stick.",
      "Joining the hot beautiful ladies of talent agancy, Levchanko Talent, LLC.",
      "Kneevis.",
      "Old Joe givin' those plums a nice squeeze.",
      "Posting my opinions on Facebook.",
      "Sending urgent funds to the Crown Prince of Nigeria.",
      "Ted Cruz.",
      "This cowboy.",
      "Using parametric statistics when the data are clearly not from a normal distribution.",
      "YOUR DOOOOOOM."
    ]
  },
  {
    "id": "picture-card-pack-2",
    "name": "Picture Card Pack 2",
    "description": "12 prompts, 18 responses from the imported CSV.",
    "prompts": [
      "______?! Good heavens!",
      "Bitch please. I invented ______.",
      "Every day, I'm grateful for ______.",
      "Father, forgive me for ______.",
      "Have you seen my son, Bogdan? He leave 30 years ago to look for ______.",
      "Its all good, dude! I've got noooo problem with ______.",
      "Mmmmm… honey… you smell like ______.",
      "These guys are ready for ______.",
      "What does this look like to you?",
      "What does this make you think about?",
      "Why is this man crying?",
      "Why is this walrus so frustrated?"
    ],
    "answers": [
      "[model on beach]",
      "[pooping dog]",
      "A dance man, big guy, great moves, always dancing -- this guy.",
      "A guy who's probably racist.",
      "A perfectly regular duck with nothing wrong with it.",
      "A yam.",
      "Eating a man's brain for$10,000.",
      "Horse yoga.",
      "Legs.",
      "ME, YOUR SON!",
      "My stinky pussy!",
      "Regret.",
      "Soulgasming.",
      "Taking shrooms with this guy.",
      "The Cactus of Ultimate Sexual Pleasure.",
      "The secrets we all hide in our big pants.",
      "Tubes.",
      "Your red-hot pecker."
    ]
  },
  {
    "id": "climate-catastrophe-pack",
    "name": "Climate Catastrophe Pack",
    "description": "5 prompts, 26 responses from the imported CSV.",
    "prompts": [
      "Al Gore is giving the world a wake-up call with his new documentary, \"A Inconvenient Truth About __________.\"",
      "BREAKING NEWS: Florida destroyed by __________.",
      "Greta Thunberg hates __________.",
      "New from David Attenborough, Planet Earth III: __________.",
      "What's a simple solution to all of humanities problems?"
    ],
    "answers": [
      "36 billion metric tons of CO2.",
      "A chart that just says \"SHIT BAD.\"",
      "A massive, coordinated international effort to stop climate change.",
      "Ball sweat.",
      "Dead whales all over the place.",
      "Eating grandma to survive.",
      "Empty promises and half measures.",
      "Everybody giving Al Gore the apology-blowjob he deserves.",
      "Fucking a tree.",
      "Getting hurled into a wildfire by a hurricane.",
      "Giving billions of taxpayer dollars to oil companies.",
      "Hot.",
      "Human extinction.",
      "Ignoring climate change and hoping it goes away.",
      "Living in a pineapple under the sea, because of climate change.",
      "Not believing in science.",
      "OH MY GOD WE'RE ALL GOING TO DIE.",
      "Plastic.",
      "Post-apocalyptic bear-cockroaches.",
      "Regulatory capture.",
      "Sucking the farts out of a cow's butthole.",
      "The Great Pacific Garbage Patch.",
      "The increasingly depressing narration in nature documentaries.",
      "The world going to shit.",
      "Titty sweat.",
      "Trying to stop climate change with weird chemicals, but accidentally creating a new ice age, and now the only surviving humans are stuck on a cyberpunk murder-train."
    ]
  },
  {
    "id": "scary-pack",
    "name": "Scary Pack",
    "description": "5 prompts, 25 responses from the imported CSV.",
    "prompts": [
      "\"I think I'm safe,\" she whispered. But then, out of nowhere, ______!",
      "Anne screamed. On her mirror was a message scrawled in blood: \"I AM ______.\"",
      "Guillermo Del Toro is the master of supernatural horror, but even he is afraid of ______.",
      "OH SHIT! ______ comin' out of Jumanji!",
      "Tonight on Murder Files: An ordinary man, driven to kill by ______."
    ],
    "answers": [
      "A big misunderstanding involving decapitations.",
      "A CD of haunted sound effects.",
      "A cursed Fleshlight that makes you rapidly age when you fuck it.",
      "A gremlin who spanks your wonderful ass with a fly swatter.",
      "A mannequin that gets a little closer every time you look away.",
      "Agonizingly transforming into a trombone.",
      "An iguana that says \"Ooh la la!\" in a threatening way.",
      "Awakening an ancient evil.",
      "Chanting in Latin.",
      "Crawling all over the walls and ceiling like a dumbass.",
      "Farting the X-Files theme.",
      "Getting disemboweled.",
      "Having unprotected sex with The Blob.",
      "Human sacrifice.",
      "Knowing a bit too much about serial killers.",
      "Night, the scariest half of the day.",
      "Pus.",
      "Putting the lotion on its skin.",
      "Realizing Mom and Dad are now at an age where it wouldn't be that unusual for them to die.",
      "Serving a man his own testicles on a sizzling fajita platter.",
      "Skulls and spiderwebs and shit.",
      "Testing negative for being alive.",
      "The current state of American democracy.",
      "The ghostly specter of a delicious six-foot party sub that disappears when you try to take a bite.",
      "Vagina dentata."
    ]
  },
  {
    "id": "picture-pack-3",
    "name": "Picture Pack 3",
    "description": "8 prompts, 22 responses from the imported CSV.",
    "prompts": [
      "10-23, this is Officer monroe requesting immediate backup. We've got a situation involving ______.",
      "HELLO WELCOME TO BUSINESS ARE YOU LOOKING FOR ______?",
      "How are we feeling today, Mrs. Rosenberg? Are we still having trouble with ______?",
      "I HAVE ______.",
      "Introducing Marvel's newest hero, Thunt the Scoundrel! His super power is ______.",
      "Timmy plays the drums so he doesn't have to think about ______.",
      "What's the name of their band?",
      "You're probably wondering, how did I get here? Well let me tell you a little story about ______."
    ],
    "answers": [
      "An all-night fuck sesh with your dad's client Robert.",
      "Asian representation.",
      "Bald Taylor Swift.",
      "Beard.",
      "Becoming a man.",
      "COVID-34.",
      "Finding out that my dad is my brother and my mom is my father and my sister is my mother and also I'm their dog.",
      "Giving everyone a the nursing home chlamydia.",
      "Going to shake a guy's hand, noticing that his hand is a fish, and pretending not to notice that his hand is a fish.",
      "Hamcube.",
      "Leaping Joosep, the Estonian version of Spider-Man.",
      "Mommy.",
      "My beautiful log.",
      "Paying $216,000 for this NFT.",
      "Some white lady dying, who cares.",
      "Swamp dick.",
      "The dick vein on the Snickers bar.",
      "The lizard that bit off Jimmy Carter's penis.",
      "Tomatoes.",
      "Tucker Carlson.",
      "Watching you masturbate.",
      "What I'm about to do to this stuffed crab."
    ]
  },
  {
    "id": "clam-pack",
    "name": "Clam Pack",
    "description": "3 prompts, 27 responses from the imported CSV.",
    "prompts": [
      "LOSE WEIGHT and FEEL GREAT with the ALL-NEW CLAM-O-NAISE® DIET! It's just Clam-O-Naise® and ______.",
      "That's right! We put ______ in mayonnaise.",
      "When I think of Clam-O-Naise®, I think about ______."
    ],
    "answers": [
      "A garbage bag full of mayonnaise.",
      "A perfectly normal rimjob that doesn't involve clams or mayonnaise in any way.",
      "Cholesterol.",
      "Clam-O-Naise®.",
      "Dr. Mayonnaise, the doctor who injects his patients with mayonnaise.",
      "Eating shellfish out of defiance of God's will.",
      "Force-feeding mayonnaise to Tom Holland.",
      "Fucking a clam out of curiosity.",
      "Just the right amount of mayonnaise.",
      "Keepin' it smooth and creamy.",
      "KNIFE-CLAM, the clam that stabs.",
      "MayooooooOOOONAISE!!!",
      "My beautiful daughter, Salmonella.",
      "My clamfather [a picture of a clam on sand]",
      "Not even knowing what's happening anymore.",
      "Not having sex with a clam under any circumstances, no matter how sexy it looks.",
      "Sneaking 700 steamed clams into a movie theater.",
      "Sodium benzoate (to preserve freshness).",
      "Some kind of mayonnaise baptism.",
      "Sticking a tube up a cow's ass to collect its mayonnaise.",
      "The all-new CLAMWICH, only at Subway!",
      "The remarkable effectiveness of mayonnaise as a sexual lubricant.",
      "The sexual possibilities of coleslaw.",
      "The United States Strategic Mayonnaise Reserve.",
      "This kind of clam. [A man holding a geoduck]",
      "Tucker Carlson debating a clam on live television.",
      "White people food."
    ]
  },
  {
    "id": "cultural-wars-pack",
    "name": "Cultural Wars Pack",
    "description": "3 prompts, 27 responses from the imported CSV.",
    "prompts": [
      "BREAKING NEWS: HUNTER BIDEN _______!",
      "If the RADICAL LEFT gets their way, they'll cancel _______!",
      "Stop trying to blame this on guns. Mass shootings are really caused by _______!"
    ],
    "answers": [
      "Abstinence-only sex education.",
      "Arguing about whether gay cops get to march in Pride.",
      "Calling Grandma a \"fascist bimbo.\"",
      "Christopher Columbus.",
      "Dead cops.",
      "Expressing offensive views behind closed doors with longtime friends.",
      "Gender-affirming surgery.",
      "Getting mad at someone for not getting mad enough about what I'm mad about.",
      "Googling \"how to do an at-home abortion.\"",
      "Grooming minors.",
      "Hunter Biden's cock.",
      "January 6th, 2021.",
      "Making it about race.",
      "Marjorie Taylor Greene.",
      "My constitutional right to carry a concealed submachine gun into Chipotle.",
      "Nazis being a thing again.",
      "Pedophile Island.",
      "Pretending to be a Native American.",
      "Privilege.",
      "Scanning a QR code to learn more about how Home Depot is celebrating LGBTQ voices.",
      "Shameless hypocrisy.",
      "Stuffing Tucker Carlson in the microwave and pressing \"potato.\"",
      "Tattooing my balls blue and yellow in solidarity with Ukraine.",
      "The Wuhan Institute of Virology.",
      "Today's mass shooting.",
      "Using the word \"Latinx.\"",
      "Using they/them pronouns."
    ]
  },
  {
    "id": "2012-holiday-pack",
    "name": "2012 Holiday Pack",
    "description": "7 prompts, 23 responses from the imported CSV.",
    "prompts": [
      "After blacking out during New Year's Eve, I was awoken by ______.",
      "Every Christmas, my uncle gets drunk and tells the story about ______.",
      "Jesus is ______.",
      "On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and ______.",
      "This holiday season, Tim Allen must overcome his fear of ______ to save Christmas.",
      "Wake up, America. Christmas is under attack by secular liberals and their ______.",
      "What keeps me warm during the cold, cold winter?"
    ],
    "answers": [
      "A Christmas stocking full of coleslaw.",
      "A Hungry-Man™ Frozen Christmas Dinner for One.",
      "A toxic family environment.",
      "A visually arresting turtleneck.",
      "Another shitty year.",
      "Clearing a bloody path through Walmart with a scimitar.",
      "Eating an entire snowman.",
      "Elf cum.",
      "Fucking up \"Silent Night\" in front of 300 parents.",
      "Gift-wrapping a live hamster.",
      "Immaculate conception.",
      "Krampus, the Austrian Christmas monster.",
      "Mall Santa.",
      "My hot cousin.",
      "Pretending to be happy.",
      "Santa's heavy sack.",
      "Several intertwining love stories featuring Hugh Grant.",
      "Socks.",
      "Space Jam on VHS.",
      "Taking down Santa with a surface-to-air missile.",
      "The Star Wars Holiday Special.",
      "The tiny, calloused hands of the Chinese children that made this card.",
      "Whatever Kwanzaa is supposed to be about."
    ]
  },
  {
    "id": "2013-holiday-pack",
    "name": "2013 Holiday Pack",
    "description": "7 prompts, 21 responses from the imported CSV.",
    "prompts": [
      "Because they are forbidden from masturbating, Mormons channel their repressed sexual energy into ______.",
      "Blessed are you, Lord our God, creator of the universe, who has granted us ______.",
      "GREETINGS HUMANS I AM ______ BOT EXECUTING PROGRAM.",
      "I really hope my grandma doesn’t ask me to explain ______ again.",
      "Kids these days with their iPods and their Internet. In my day, all we needed to pass the time was ______.",
      "Revealed: Why He Really Resigned! Pope Benedict’s Secret Struggle with ______.",
      "What’s the one thing that makes an elf instantly ejaculate?"
    ],
    "answers": [
      "A magical tablet containing a world of unlimited pornography.",
      "A simultaneous nightmare and wet dream starring Sigourney Weaver.",
      "Being blind and deaf and having no limbs.",
      "Breeding elves for their priceless semen.",
      "Congress’s flaccid penises withering away beneath their suit pants.",
      "Finding out Santa isn’t real.",
      "Giving money and personal information to strangers on the Internet.",
      "Having a strong opinion about Obamacare.",
      "Jizzing into Santa’s beard.",
      "Making up for 10 years of shitty parenting with a PlayStation.",
      "Moses gargling Jesus’s balls while Shiva and the Buddha penetrate his divine hand holes.",
      "People with cake in their mouths talking about how good cake is.",
      "Piece of shit Christmas cards with no money in them.",
      "Rudolph’s bright red balls.",
      "Slicing a ham in icy silence.",
      "Swapping bodies with mom for a day.",
      "The Grinch’s musty, cum-stained pelt.",
      "The Hawaiian goddess Kapo and her flying detachable vagina.",
      "The royal afterbirth.",
      "The shittier, Jewish version of Christmas.",
      "These low, low prices!"
    ]
  },
  {
    "id": "2014-holiday-pack",
    "name": "2014 Holiday Pack",
    "description": "5 prompts, 24 responses from the imported CSV.",
    "prompts": [
      "Behold the Four Horsemen of the Apocalypse! War, Famine, Death, and ______.",
      "Dear Mom and Dad, Camp is fun. I like capture the flag. Yesterday, one of the older kids taught me about ______. I love you, Casey",
      "Here lies First Last, Year-2015, devoted friend, lover of ______.",
      "Honey, Mommy and Daddy love you very much. But apparently Mommy loves ______ more than she loves Daddy.",
      "Why am I so tired?"
    ],
    "answers": [
      "200 years of slavery.",
      "A cloud of ash that darkens the Earth for a thousand years.",
      "A protracted siege.",
      "A vague fear of something called ISIS.",
      "All the poop inside of my body.",
      "Being replaced by a robot.",
      "Blockbuster late fees up the wazoo.",
      "Building a ladder of hot dogs to the moon.",
      "Ebola.",
      "Harnessing the miraculous power of the atom to slaughter 200,000 Japanese people.",
      "Reading an entire book.",
      "Rising sea levels consistent with scientific predictions.",
      "Rock music and premarital sex.",
      "Small-town cops with M-4 assault rifles.",
      "The 9,000 children who starved to death today.",
      "The Bowflex Revolution.",
      "The diminishing purity of the white race.",
      "The dying breath of the last human.",
      "The events depicted in James Cameron's Avatar.",
      "The Great Lizard Uprising of 2352.",
      "The transience of all things.",
      "This groovy new thing called LSD.",
      "Trying to feel something, anything.",
      "What remains of my penis."
    ]
  },
  {
    "id": "jew-pack-chosen-people-pack",
    "name": "Jew Pack/Chosen People Pack",
    "description": "5 prompts, 25 responses from the imported CSV.",
    "prompts": [
      "According to Freud, all children progress through three stages of development: the oral stage, the anal stage, and the ______ stage.",
      "Can't you see? The Jews are behind everything-the banks, the media, even ______!",
      "Coming to Broadway next season: \"______ on the Roof.\"",
      "Oh, your daughter should meet my son! He gives to charity, he loves ______ and did I mention he's a doctor?",
      "What's so important right now that you can't call your mother?"
    ],
    "answers": [
      "A big brain full of facts and sadness.",
      "A headache that's definitely cancer.",
      "A lifetime of internalized guilt.",
      "A little bit of schmutz right there.",
      "A three-foot-tall corned beef sandwich.",
      "Bags of money.",
      "Being chosen by God to win a free iPod Nano.",
      "Chopping off a bit of the penis.",
      "Demolishing that ass like a Palestinian village.",
      "Hiding from the Nazis.",
      "Holding up the line at Walgreens by trying to use an expired coupon.",
      "Pork products.",
      "Resurrecting an army of six million Jews and conquering Germany.",
      "Sacrificing Isaac to the Lord.",
      "Some kind of concentrated encampment for people.",
      "Suddenly remembering that the Holocaust happened.",
      "The blood of Christian babies.",
      "The ethical implications of enjoying a Woody Allen film in light of the allegations against him.",
      "The part of Anne Frank's diary where she talks about her vagina.",
      "Thy neighbor's wife.",
      "Torturing Jews until they say they're not Jews anymore.",
      "Usury.",
      "Wandering the desert for 40 years.",
      "What it means to be a Jewish woman in contemporary society.",
      "Whoopi Goldberg."
    ]
  },
  {
    "id": "seasons-greetings-pack",
    "name": "Seasons Greetings Pack",
    "description": "3 prompts, 12 responses from the imported CSV.",
    "prompts": [
      "Donna, pick up my dry cleaning and get my wife something for Christmas. I think she likes _____.",
      "It's beginning to look a lot like _____.",
      "You love Black Friday. You love Cyber Monday. So don’t miss _____ Wednesday, only at Kohl’s!"
    ],
    "answers": [
      "A choir of angels descending from the sky and jizzing all over dad's sweater.",
      "A frozen homeless man shattering on your doorstep.",
      "A snowman that contains the soul of my dead father.",
      "Capitalism",
      "Finding out that Santa isn't real.",
      "How cool it is that I love Jesus and he loves me back.",
      "How great of a blowjob Jesus could give.",
      "How many drinks Aunty Deborah has had.",
      "My uncle who voted for Trump.",
      "Probably Grandma's last Christmas, kids.",
      "Snow falling gently on the frozen body of an orphan boy.",
      "Starting to see where ISIS is coming from."
    ]
  },
  {
    "id": "hawaii-2-safe-cards",
    "name": "Hawaii 2 Safe Cards",
    "description": "0 prompts, 2 responses from the imported CSV.",
    "prompts": [],
    "answers": [
      "Being the crazy person who opened the safe.",
      "Sloth card."
    ]
  },
  {
    "id": "pax-2012-oops-kit",
    "name": "PAX 2012 \"Oops\" Kit",
    "description": "5 prompts, 9 responses from the imported CSV.",
    "prompts": [
      "______: good to the last drop.",
      "Daddy, why is Mommy crying?",
      "Dear Abby, I'm having some trouble with ______ and would like your advice.",
      "I drink to forget ______.",
      "White people like ______."
    ],
    "answers": [
      "A Bitch Slap.",
      "Chunks of dead prostitute.",
      "Extremely tight pants.",
      "One trillion dollars.",
      "Stormtroopers.",
      "The Boy Scouts of America.",
      "The entire Mormon Tabernacle Chior.",
      "The female orgasm.",
      "Throwing a virgin into a volcano."
    ]
  },
  {
    "id": "pax-east-2013-promo-pack-a",
    "name": "PAX East 2013 Promo Pack A",
    "description": "2 prompts, 8 responses from the imported CSV.",
    "prompts": [
      "I have an idea even better than Kickstarter, and it's called ______starter.",
      "You have been waylaid by ______ and must defend yourself."
    ],
    "answers": [
      "An immediately regrettable $9 hot dog from the Boston Convention Center.",
      "Casting Magic Missile at a bully.",
      "Firefly: Season 2.",
      "Getting bitch slapped by Dhalsim.",
      "Jiggle physics.",
      "Paying the iron price.",
      "Rotating shapes in mid-air so that they fit into other shapes when they fall.",
      "Running out of stamina."
    ]
  },
  {
    "id": "pax-east-2013-promo-pack-b",
    "name": "PAX East 2013 Promo Pack B",
    "description": "2 prompts, 8 responses from the imported CSV.",
    "prompts": [
      "Action stations! Action stations! Set condition one throughout the fleet and brace for ______!",
      "In the final round of this year's Omegathon, Omeganauts must face off in a game of ______."
    ],
    "answers": [
      "Getting inside the Horadric Cube with a hot babe and pressing the transmute button.",
      "Loading from a previous save.",
      "Punching a tree to gather wood.",
      "Sharpening a foam broadsword on a foam whetstone.",
      "Spending the year's insulin budget on Warhammer 40k figurines.",
      "The depression that ensues after catching 'em all.",
      "The rocket launcher.",
      "Violating the First Law of Robotics."
    ]
  },
  {
    "id": "pax-east-2013-promo-pack-c",
    "name": "PAX East 2013 Promo Pack C",
    "description": "2 prompts, 8 responses from the imported CSV.",
    "prompts": [
      "I don't know exactly how I got the PAX plague, but I suspect it had something to do with ______.",
      "Press ↓ ↓ ← → B to unleash ______."
    ],
    "answers": [
      "Achieving 500 actions per minute.",
      "Charging up all the way.",
      "Forgetting to eat, and consequently dying.",
      "Judging elves by the color of their skin and not by the content of their character.",
      "Smashing all the pottery in a Pottery Barn in search of rupees.",
      "The Klobb.",
      "Vespene gas.",
      "Wil Wheaton crashing an actual spaceship."
    ]
  },
  {
    "id": "pax-prime-2013",
    "name": "PAX Prime 2013",
    "description": "7 prompts, 37 responses from the imported CSV.",
    "prompts": [
      "______: Achievement unlocked.",
      "In the new DLC for Mass Effect, Shepard must save the galaxy from ______.",
      "No Enforcer wants to manage the panel on ______.",
      "The most controversial game at PAX this year is an 8-bit indie platformer about ______.",
      "There was a riot at the Gearbox panel when they gave the attendees ______.",
      "What made Spock cry?",
      "What's the latest bullshit that's troubling this quaint fantasy town?"
    ],
    "answers": [
      "70,000 gamers sweating and farting inside an airtight steel dome.",
      "A fully-dressed female videogame character.",
      "A homemade, cum-stained Star Trek uniform.",
      "A madman who lives in a policebox and kidnaps women.",
      "Achieving the manual dexterity and tactical brilliance of a 12-year-old Korean boy.",
      "Allowing nacho cheese to curdle in your beard while you creep in League of Legends.",
      "An angry stone head that stomps on the floor every three seconds.",
      "Being an attractive elf trapped in an unattractive human's body.",
      "Bowser's aching heart.",
      "Buying virtual clothes for a Sim family instead of real clothes for a real family.",
      "Charles Barkley Shut Up and Jam!",
      "Eating a pizza that's lying in the street to gain health.",
      "Filling every pouch of a UtiliKilt™ with pizza.",
      "Full HD.",
      "Getting into a situation with an owlbear.",
      "Google Glass + e-cigarette: Ultimate Combo!",
      "Grand Theft Auto: Fort Lauderdale.",
      "Legendary Creature - Robert Khoo.",
      "Mario Kart rage.",
      "Never watching, discussing, or thinking about My Little Pony.",
      "Nude-modding Super Mario World.",
      "Offering sexual favors for an ore and a sheep.",
      "Reading the comments.",
      "Rolling a D20 to save a failing marriage.",
      "SNES cartridge cleaning fluid.",
      "Tapping Serra Angel.",
      "Temporary invincibility.",
      "The boner hatch in the Iron Man suit.",
      "The Cock Ring of Alacrity.",
      "The collective wail of every Magic player suddenly realizing that they've spent hundreds of dollars on pieces of cardboard.",
      "The decade of legal inquests following a single hour of Grand Theft Auto.",
      "The gravity gun.",
      "The Sarlacc.",
      "Turn-of-the-century sky racists.",
      "Unlocking a new sex position.",
      "Winning the approval of Cooking Mama that you never got from actual mama.",
      "Yoshi's huge egg-laying cloaca."
    ]
  },
  {
    "id": "pax-east-2014",
    "name": "PAX East 2014",
    "description": "4 prompts, 22 responses from the imported CSV.",
    "prompts": [
      "(Heavy breathing) Luke, I am ______.",
      "Unfortunately, Neo, no one can be told what ______ is. You have to see it for yourself.",
      "What the hell?! They added a 6/6 with flying, trample and ______.",
      "You think you have defeated me? Well, let's see how you handle ______."
    ],
    "answers": [
      "A giant mechanical bird with a tragic backstory.",
      "A grumpy old Harrison Ford who'd rather be doing anything else.",
      "All of the good times and premium gaming entertainment available to you in the Kickstarter room.",
      "Attacking from Kamchatka.",
      "Collecting all seven power crystals.",
      "Demons and shit.",
      "Endless ninjas.",
      "Futuristic death sports.",
      "Getting bitten by a radioactive spider and then battling leukemia for 30 years.",
      "KHAAAAAAAAAN!",
      "Lagging out.",
      "Mistakenly hitting on a League of Legends statue.",
      "Separate drinking fountains for dark elves.",
      "Ser Jorah Mormont's cerulean-blue balls.",
      "Stuffing my balls into a Sega Genesis and pressing the power button.",
      "Taking 2d6 emotional damage.",
      "The imagination of Peter Jackson.",
      "The old gods.",
      "The pure, Zen-like state that exists between micro and macro.",
      "The Star Wars universe.",
      "Whatever Final Fantasy bullshit happened this year.",
      "Xena, Warrior Princess."
    ]
  },
  {
    "id": "pax-east-2014-panel-cards",
    "name": "PAX East 2014 - Panel Cards",
    "description": "1 prompts, 7 responses from the imported CSV.",
    "prompts": [
      "______ was totally worth the trauma."
    ],
    "answers": [
      "A floor that is literally made of lava.",
      "All this liquid in my mouth.",
      "Exciting content!",
      "Giving a dolphin a handjob for science.",
      "Rubbing chocolate pudding all over Bill Cosby's nipples.",
      "Stepping on a god damn friggin' LEGO.",
      "What The Rock was really cooking."
    ]
  },
  {
    "id": "pax-prime-2014-panel-cards",
    "name": "PAX Prime 2014 - Panel Cards",
    "description": "4 prompts, 5 responses from the imported CSV.",
    "prompts": [
      "Bob Ross's little-known first show was called \"The Joy of ______.\"",
      "During my first game of D&D, I accidentally summoned ______.",
      "Like ______, State Farm is there.",
      "The Discovery Channel presents: ______ week."
    ],
    "answers": [
      "A neck beard that is 10% cheese.",
      "No survivors.",
      "Pelvic sorcery.",
      "Pooping as quietly as possible.",
      "The beautiful sport of Turkish oil wrestling."
    ]
  },
  {
    "id": "pax-prime-2014-custom-printed-cards",
    "name": "PAX Prime 2014 Custom Printed Cards",
    "description": "1 prompts, 45 responses from the imported CSV.",
    "prompts": [
      "What's the weirdest thing that AdMagic has printed?"
    ],
    "answers": [
      "Go Fuck Yourself.",
      "100% certified human breast milk.",
      "A bunch of weeaboos buying Nature Valley bars.",
      "A drunken Sailor Pluto.",
      "A gloryhole with a serrated edge.",
      "A little person dressed as a baby punching an actual baby.",
      "A magic card worth roughly $8.",
      "A necrophiliamancer.",
      "A pint of beer half-full of dead snails.",
      "A real job with real responsibilities.",
      "A Stark family where all of the children survive.",
      "A tin of worms in metric or imperial.",
      "Adrian Talens.",
      "ADVENTURE!",
      "All the Asians in Vancouver.",
      "An idiot from New Jersey who can only make friends with Bay Area scum.",
      "Assault Android Cactus.",
      "Awkwardly having to sing Happy Birthday to a stranger.",
      "Being named Gladys.",
      "Bitcoin.",
      "Bruce using the handicapped elevator even though he's a totally able-bodied person.",
      "Butthurt.",
      "Chit.",
      "Chris Evans grabbing his left boob while laughing.",
      "Classy Ewok porn.",
      "Cortana.",
      "Crippling OC D.",
      "Danny got to 2nd base with his grandma.",
      "Doing a barrel roll.",
      "Drinking with the DCD.",
      "Drymount.",
      "Dying for the 418th time in Dark Souls.",
      "Eating an entire pizza as a legit medical condition.",
      "Elli the shit-head cat.",
      "Exploding pancakes.",
      "F5.",
      "Fat bitch logic.",
      "Filming Tabletop Deathmatch.",
      "Five teenagers with attitude.",
      "Flipper.",
      "Fully appreciating naked Morris dancing.",
      "Furry porn that's actually sort of hot.",
      "Going back in time and fucking my mom to prove a point.",
      "Grandpa Dick Chin.",
      "Having nothing to prove."
    ]
  },
  {
    "id": "pax-prime-2015-food-pack-b-coconut",
    "name": "PAX Prime 2015 Food Pack B (Coconut)",
    "description": "1 prompts, 0 responses from the imported CSV.",
    "prompts": [
      "Aw babe, your burps smell like ______!"
    ],
    "answers": []
  },
  {
    "id": "pax-prime-2015-food-pack-c-cherry",
    "name": "PAX Prime 2015 Food Pack C (Cherry)",
    "description": "1 prompts, 1 responses from the imported CSV.",
    "prompts": [
      "Excuse me, waiter. Could take this back? This soup tastes like ______."
    ],
    "answers": [
      "A Mexican child trapped inside of a burrito."
    ]
  },
  {
    "id": "gen-con-2018-midterm-election-pack",
    "name": "Gen Con 2018 Midterm Election Pack",
    "description": "2 prompts, 16 responses from the imported CSV.",
    "prompts": [
      "If Mike Pence could dream, he would dream about ______.",
      "What will finally make me care?"
    ],
    "answers": [
      "41 million Americans living in poverty.",
      "A law that allows factories to dump toxic waste into children's mouths.",
      "A living wage and affordable health care.",
      "A politician who doesn't blow monkey ass.",
      "Crowdfunding my daughter's bone marrow transplant.",
      "Donald Trump's latest fucking thing.",
      "Fentanyl.",
      "Fucking over future generations.",
      "ICE.",
      "Not thinking about the children in cages.",
      "Overturning Roe v. Wade.",
      "Propping up Ruth Bader Ginsburg's corpse and moving her jaw up and down.",
      "Pseudointellectual centrist bullshit.",
      "Rising to power on a wave of ethnic nationalism.",
      "Sean Spicer, Reince Priebus, Steve Bannon, Sebastian Gorka, Omarosa, Anthony Scaramucci, James Comey, Mike Flynn, Rex Tillerson, Ty Cobb, Andrew McCabe, K. T. McFarland, H. R. McMaster, Gary Cohn, Hope Hicks, Rob Porter, Scott Pruitt, and Tom Price.",
      "Totally ineffective political satire."
    ]
  },
  {
    "id": "jack-white-show-pack",
    "name": "Jack White Show Pack",
    "description": "1 prompts, 6 responses from the imported CSV.",
    "prompts": [
      "When Jack White performed at the Aragon Ballroom in Chicago on Nov. 19, 2018, he surprised fans with _____."
    ],
    "answers": [
      "A quiet, poignant acoustic guitar ballad.",
      "Jack White’s collection of taxidermied animal heads.",
      "Jack White’s testosterone-fueled dementia.",
      "Jack White’s mom coming on stage and dancing.",
      "A bizarre partnership with Cards Against Humanity.",
      "Jack White."
    ]
  },
  {
    "id": "reject-pack",
    "name": "Reject Pack",
    "description": "8 prompts, 16 responses from the imported CSV.",
    "prompts": [
      "From WBEZ Chicago, it's This American Life. Today on our program, ______. Stay with us.",
      "My name is Inigo Montoya. You killed my father. Prepare for ______.",
      "Sir, we found you passed out naked on the side of the road. What's the last thing you remember?",
      "The elders of the Ibo tribe of Nigeria recommend ______ as a cure for impotence.",
      "The Westboro Baptist Church is now picketing soldiers' funerals with signs that read 'GOD HATES ______!'",
      "What are two cards in your hand that you want to get rid of?",
      "What do you see? [An image of a Rorschach inkblot]",
      "You can't wait forever. It's time to talk to your doctor about ______."
    ],
    "answers": [
      "A giant squid in a wedding gown.",
      "A heart that is two sizes too small and that therefore cannot pump an adequate amount of blood.",
      "A sexy naked interactive theater thing.",
      "Asshole pomegranates that are hard to eat.",
      "Becoming so rich that you shed your body and turn to vapor.",
      "Carribbean Jesus.",
      "Corn.",
      "Crawling into a vagina.",
      "Dividing by zero.",
      "Ejaculating a pound of tinsel.",
      "Faking a jellyfish sting so someone will pee on you.",
      "Ladles.",
      "My dick in your mouth.",
      "Playing an ocarina to summon Ultra-Congress from the sea.",
      "Super yoga.",
      "The John D. and Catherine T. MacArthur Foundation."
    ]
  },
  {
    "id": "reject-pack-2",
    "name": "Reject Pack 2",
    "description": "10 prompts, 24 responses from the imported CSV.",
    "prompts": [
      "Astronomers have discovered that the universe consists of 5% ordinary matter, 25% dark matter, and 70% ______.",
      "BowWOW! is the first pet hotel in LA that offers ______ for dogs.",
      "Hey, whatever happened to Renee Zellweger?",
      "Housekeeping! You want ______?",
      "In bourgeois society, capital is independent and has individuality, while the living person is ______.",
      "Some men aren't looking for anything logical, like money. They can't be bought, bullied, reasoned or negotiated with. Some men just want ______.",
      "What's wrong with these gorillas?",
      "Why did the chicken cross the road?",
      "You say tomato, I say ______.",
      "America is hungry. America needs ______."
    ],
    "answers": [
      "A dick so big and so black that not even light can escape its pull.",
      "A double murder suicide barbeque.",
      "A primordial soup and salad bar.",
      "A stack of bunnies in a trenchcoat.",
      "At least three ducks.",
      "Becoming engorged with social justice jelly and secreting a thinkpiece.",
      "Being the absolute worst.",
      "Disco Mussolini.",
      "Greg Kinnear's terrible lightning breath.",
      "Mitt Romney's eight sons Kip, Sam, Trot, Fergis, Toolshed, Grisham, Hawkeye, and Thorp.",
      "Mr. and Mrs. Tambourine Man's jingle-jangle morning sex.",
      "Mushy tushy.",
      "Ringo Starr & His All-Starr Band.",
      "Sandwich.",
      "Saving the Rainforest Cafe.",
      "Sir Thomas More's Fruitopia™.",
      "Sweating it out on the streets of a runaway American Dream.",
      "That one leftover screw.",
      "That thing politicians do with their thumbs when they talk.",
      "The spooky skeleton under my skin.",
      "The token lesbian.",
      "These dolphins.",
      "Three hairs from the silver-golden head of Galadriel.",
      "Water so cold it turned into a rock."
    ]
  },
  {
    "id": "house-of-cards-pack",
    "name": "House of Cards Pack",
    "description": "7 prompts, 16 responses from the imported CSV.",
    "prompts": [
      "A wise man said, \"Everything is about sex. Except sex. Sex is about ______.\"",
      "Cancel all my meetings. We've got a situation with ______ that requires my immediate attention.",
      "I can't believe Netflix is using ______ to promote House of Cards.",
      "I'm not going to lie. I despise ______. There, I said it.",
      "If you need him to, Remy Danton can pull some strings and get you ______, but it'll cost you.",
      "Our relationship is strictly professional. Let's not complicate things with ______.",
      "We're not like other news organizations. Here at Slugline, we welcome ______ in the office."
    ],
    "answers": [
      "25 shitty jokes about House of Cards.",
      "A childless marriage.",
      "A homoerotic subplot.",
      "A much younger woman.",
      "An older man.",
      "An origami swan that's some kind of symbol?",
      "Carbon monoxide poisoning.",
      "Discharging a firearm in a residential area.",
      "Forcing a handjob on a dying man.",
      "Getting eaten out while on the phone with Dad.",
      "Making it look like a suicide.",
      "My constituents.",
      "Punching a congressman in the face.",
      "Ribs so good they transcend race and class.",
      "Strangling a dog to make a point to the audience.",
      "The sensitive European photographer who's fucking my wife."
    ]
  },
  {
    "id": "tabletop-pack",
    "name": "Tabletop Pack",
    "description": "3 prompts, 12 responses from the imported CSV.",
    "prompts": [
      "Backers who supported Tabletop at the $25,000 level were astonished to receive ______ from Wil Wheaton himself.",
      "For my turn, I will spend four gold and allocate all three workers to ______.",
      "Hey, you guys want to try this awesome new game? It’s called ______."
    ],
    "answers": [
      "A disappointing season of Tabletop that's just about tables.",
      "A German-style board game where you invade Poland.",
      "A marriage-destroying game of The Resistance.",
      "A Wesley Crusher blow-up doll.",
      "A zombie with a tragic backstory.",
      "An owlbear.",
      "Condensing centuries of economic exploitation into 90 minutes of gaming fun.",
      "SIX GOD DAMN HOURS OF FUCKING DIPLOMACY.",
      "The pooping position.",
      "The porn set that Tabletop is filmed on.",
      "Victory points.",
      "Spending 8 years in the Himalayas becoming a master of dice-rolling and resource allocation."
    ]
  },
  {
    "id": "trump-bug-out-bag-post-trump-pack",
    "name": "Trump Bug Out Bag/Post-Trump Pack",
    "description": "3 prompts, 22 responses from the imported CSV.",
    "prompts": [
      "Donald Trump has nominated ______ for his VP.",
      "In 2019, Donald Trump eliminated our national parks to make room for ______.",
      "Donald Trump's first act as presidnet was to outlaw ______."
    ],
    "answers": [
      "A legitimate reason to commit suicide.",
      "A back-alley abortion from a Mexican cyborg doctor.",
      "Whipping lower-class white men into a xenophobic frenzy.",
      "Rage.",
      "Trying to remember what music was.",
      "Roaming through a wasteland of windblown trash and deserted highways.",
      "Bringing millions of dangerous low-paying manufacturing jobs back to America.",
      "A gnawing sense of dread.",
      "Drinking urine to survive.",
      "Nuclear winter.",
      "President Donald Trump.",
      "Casual dismissiveness.",
      "Extra rations for my little girl.",
      "World Wars 3 through 5.",
      "Finding out that democracy might not be such a great idea.",
      "Mild amusement.",
      "Burying my only son.",
      "The purging of the disloyal.",
      "Trying to wake up from this nightmare.",
      "A father and son fighting each other over the last scrap of bread.",
      "Making Islam illegal.",
      "Desperately hurling insults at Donald Trump as he absorbs them into his rapidly expanding body."
    ]
  },
  {
    "id": "fascism-pack",
    "name": "Fascism Pack",
    "description": "2 prompts, 14 responses from the imported CSV.",
    "prompts": [
      "Before swallowing his pride and a cyanide pill, Adolf whispered to Eva, \"Sorry about ______\".",
      "Leni Riefenstahl's last movie was called Triumph of ______."
    ],
    "answers": [
      "An orgasm so powerful you travel back in time and jizz in Hitler's face.",
      "Being open to new perspectives on the Holocaust.",
      "Breaking news about what Hitler's penis was like.",
      "Cloning Hitler.",
      "Donald Trump's personal copy of Mein Kampf.",
      "Electro-Stalin.",
      "Hitler's sound economic policies.",
      "How cool Nazi airplanes are.",
      "Presenting your documents at a checkpoint.",
      "Runining an entire genre of moustaches.",
      "Straight up fucking loving authority.",
      "The cyanide pill you keep on your person at all times.",
      "The Yad Vashem World Center for Holocaust Research.",
      "Whatever brave hero killed Hitler."
    ]
  },
  {
    "id": "hanukkah-lol-pack",
    "name": "Hanukkah LOL Pack",
    "description": "0 prompts, 7 responses from the imported CSV.",
    "prompts": [],
    "answers": [
      "A smile or just a nod.",
      "All the accumulated culture of a people.",
      "Being young and living in New York City.",
      "The dark side.",
      "The gross inequalities of our society.",
      "The wisdom of the crowds.",
      "Uninformed knuckle-dragging low information voters."
    ]
  },
  {
    "id": "mass-effect-pack",
    "name": "Mass Effect Pack",
    "description": "4 prompts, 10 responses from the imported CSV.",
    "prompts": [
      "Coming this spring from BioWare, Mass Effect: ______.",
      "I'm Commander Shepard, and this is my favorite place for ______ on the Citadel.",
      "It turns out the Reapers didn't want to destroy the galaxy. They just wanted ______.",
      "We were the two best hand-to-hand combatants on the ship. I had reach, but she had ______."
    ],
    "answers": [
      "An armored Krogan war-clitoris.",
      "An emergency induction port.",
      "An extremely long elevator ride.",
      "Bone-shattering sex with a metal woman.",
      "Falling I actual love with a video game character.",
      "My complicated backstory that you will soon learn about.",
      "Running a few errands before saving the galaxy.",
      "Space racism.",
      "The Genophage.",
      "Totally fuckable aliens."
    ]
  },
  {
    "id": "retail-product-pack",
    "name": "Retail Product Pack",
    "description": "1 prompts, 19 responses from the imported CSV.",
    "prompts": [
      "Wait, I came here to buy socks. How did I wind up with ______?"
    ],
    "answers": [
      "A framed photocopy of an oil painting of Paris, France.",
      "A Pringle.®",
      "A Pringles® can full of screams.",
      "An 800-foot-long pool noodle.",
      "An exclusive partnership with Taylor Swift.",
      "Blood Pringles.®",
      "Buying and returning clothes just to have someone to talk to.",
      "Buying the right toothbrush cup for my lifestyle.",
      "Confusing possessions with accomplishments.",
      "Crunchy snacks for my big flappy mouth.",
      "Extracting the maximum amount of money from naive consumers.",
      "Gender-neutral toys that make children feel no emotions whatsoever.",
      "Getting eaten out in the family fitting room.",
      "How fun it is to eat Pringles.®",
      "Refusing to go up a size.",
      "Saving 20% or more on khakis.",
      "Shiny gadgets for sadness distraction.",
      "Subsisting on tiny pizzas.",
      "The obscene amount of money Cards Against Humanity is making by selling this game at Target.®"
    ]
  },
  {
    "id": "hidden-compartment-pack",
    "name": "Hidden Compartment Pack",
    "description": "0 prompts, 15 responses from the imported CSV.",
    "prompts": [],
    "answers": [
      "A blind, quadriplegic AIDS survivor with face cancer and diarrhea.",
      "A gossamer stream of jizz that catches the light as is arcs through the morning air.",
      "Chugging a gallon of milk and then vomiting a gallon of milk.",
      "Digging up Heath Ledger's corpse to reenact the prom scene from Ten Things I Hate About You.",
      "Eight beautiful men jerking each other off in front of a fountain.",
      "Free ice cream forever, or getting fingered by Chris Hemsworth for five minutes.",
      "Getting drugs off the street and into my body.",
      "Giving ISIS whatever they want so they leave us alone.",
      "Hickory-fucked pork ribs smothered in hot garbage.",
      "How far I can get my own penis up my butt.",
      "How wonderful it is when my master throws the ball and I go and get it for him.",
      "Ruth Bader Ginsberg brutally graveling your penis.",
      "Sitting in a jar of vinegar all night because I am pickle.",
      "Throwing a baby dolphin back into the ocean with a perfect spiral.",
      "Throwing your hands in the air and waving them despite caring deeply."
    ]
  },
  {
    "id": "vote-for-hillary-pack",
    "name": "Vote For Hillary Pack",
    "description": "3 prompts, 12 responses from the imported CSV.",
    "prompts": [
      "As repartations for slavery, all African Americans will receive ______.",
      "Senator, I trust you enjoyed ______ last night. Now, can I count on your vote?",
      "When you go to the polls on Tuesday, remember: a vote for me is a vote for ______."
    ],
    "answers": [
      "A beautiful, ever-expanding circle of inclusivity that will never include Republicans.",
      "Black lives mattering.",
      "Donald Trump holding his nose while he eats pussy.",
      "Eating the president's pussy.",
      "Increasing economic and political polarization.",
      "Keeping the government out of my vagina.",
      "Kicking the middle class in the balls with a regressive tax code.",
      "Letting Bernie Sanders rest his world-weary head on your lap.",
      "Slapping Ted Cruz over and over.",
      "The Bernie Sanders revolution.",
      "The fact that Hillary Clinton is a woman.",
      "The systematic disenfranchisement of black voters."
    ]
  },
  {
    "id": "vote-for-trump-pack",
    "name": "Vote For Trump Pack",
    "description": "3 prompts, 12 responses from the imported CSV.",
    "prompts": [
      "According to Arizona's stand-your-ground law, you're allowed to shoot someone if they're ______.",
      "It's 3AM. The red phone rings. It's ______. Who do you want answering?",
      "Trump's great! Trump's got ______. I love that."
    ],
    "answers": [
      "A liberal bias.",
      "Actually voting for Donald Trump to be President of the actual United States.",
      "Conservative talking points.",
      "Courageousely going ahead with that racist comment.",
      "Dispelling this fiction that Barack Obama doesn't know what he's doing.",
      "Full-on socialism.",
      "Growing up and becoming a Republican.",
      "Hating Hilary Clinton.",
      "Jeb!",
      "Shouting the loudest.",
      "Sound fiscal policy.",
      "The good, hardworking people of Dubuque, Iowa."
    ]
  },
  {
    "id": "desert-bus-for-hope-pack",
    "name": "Desert Bus For Hope Pack",
    "description": "4 prompts, 19 responses from the imported CSV.",
    "prompts": [
      "Desert Bus: ___ for the children.",
      "I bless ___ down in Africa.",
      "The four shifts at Desert Bus: Dawn Guard, Alpha Flight, Night Watch and ____.",
      "YOU try explaining ___ to the media!"
    ],
    "answers": [
      "$10,000 worth of silica gel.",
      "A bathroom only for poop.",
      "A chair-shaped fart sponge.",
      "A lethal dose of caffeine.",
      "Accidentally broadcasting an NSFW video to 5,000 people.",
      "An encyclopedic knowledge of Night Court.",
      "Belting out the chorus of a popular song and mumbling through the rest.",
      "Bill's mom.",
      "Desert Bus.",
      "Doing it for the children.",
      "Having no idea what the fuck is going on.",
      "Letting the internet feed you.",
      "Playing one-handed.",
      "Shipping a fish brick to Ohio.",
      "The BONE ZONE!",
      "The D E V I C E.",
      "The Turner Lickability Scale.",
      "Whale dong.",
      "William Shatner watching you."
    ]
  },
  {
    "id": "saves-america-2",
    "name": "Saves America",
    "description": "1 prompts, 4 responses from the imported CSV.",
    "prompts": [
      "Oh shit! I just got ______."
    ],
    "answers": [
      "My money stolen by Cards Against Humanity and redistributed to people poorer than me.",
      "A full refund from Cards Against Humanity, paid for by people richer than me.",
      "A $1,000 check from Cards Against Humanity!",
      "Yelling \"I got it, I got it!\""
    ]
  },
  {
    "id": "theatre-pack-cats-musical-pack",
    "name": "Theatre Pack - CATS Musical Pack",
    "description": "3 prompts, 27 responses from the imported CSV.",
    "prompts": [
      "_____! All alone in the moonlight!",
      "Ahhh _____! Toodle pip!",
      "Jellicle Cats come out tonight, Jellicle Cats come one, come all, the time for _____ is now, Jellicles come to the Jellicle Ball."
    ],
    "answers": [
      "30 grown adults crawling around on all-fours.",
      "A man who has not heard of a Jellicle cat.",
      "Becoming Mr. Mistoffelees.",
      "Bustopher Jones.",
      "Carbucketty.",
      "Feline AIDS.",
      "Garfield.",
      "Griddlebone.",
      "Grizabella, the glamour cat.",
      "Growltiger.",
      "Grump Cat.",
      "Gus: the Palsy Cat.",
      "Heathcliff.",
      "Jellicle cats.",
      "Macavity!",
      "Memory.",
      "Meow.",
      "Mungojerrie and Rumpleteazer.",
      "Munkustrap.",
      "Old Deuteronomy.",
      "Peter, Augustus, Alonzo, or James.",
      "Practical cats, dramatical cats, oratical cats, sceptical cats, romantical cats, parasitical cats, statistical cats, political cats, hypocritical cats, clerical cats, cynical cats, rabbinical cats.",
      "Rum Tum Tugger.",
      "Shimbleshanks.",
      "Sir Andrew Lloyd Webber.",
      "The mystical divinity of unashamed felinity.",
      "Winkles and shrimps."
    ]
  },
  {
    "id": "reject-pack-3",
    "name": "Reject Pack 3",
    "description": "2 prompts, 21 responses from the imported CSV.",
    "prompts": [
      "Bitch, you look nasty. You look disgusting. You look like you're ______. Go home, butch.",
      "So this family circus act comes in to see a talent agent in Hoboken, and the agent askes what they do. The father of the act jumps up and starts to furiously beat off into a towel while his wife whips her hair back and forth to that famous song - originally sung by one of Will Smith's kids, \"I Whipe My Hair Bcak And Forth\" - which her twin daughters are singing while they braid each other's pubes, all while the twin BROTHERS are creating a real-estate bubble by purchasing houses and flipping them for needless profit, and all THIS is happening while the grandmother is peeing into a Smuckers jar and slapping her ass. The whole thing ends with the family spitting into each other's assholes. The talent agent can't believe it. He looks at the sweaty father who has just spit into his mother's asshole and says. \"WOW. This is great. Whaddya call yourselves?\" And the guy looks at him and says, \"We're ______.\""
    ],
    "answers": [
      "A child's love of sticks.",
      "A man two times the size of a man half his size.",
      "Abandoning all concepts and categories and seeing the world as it truly is.",
      "Achieving total fitness and turning into a mental cube.",
      "Being blind but having super strength but having Alzheimer's Disease by being invisible.",
      "Collapsing into singularity. Twenty minutes fo foreplay, three minutes of coitus, five minutes of rest, back to the yards for some croquet.",
      "Computers.",
      "Cum, but it's ranch.",
      "Fashion… heard of if?",
      "Getting my mind boggled by a gang of mind bogglers.",
      "Letting these hoes know.",
      "Meatballs, meatballs, meatballs!",
      "Passing fart and making toilet.",
      "Sheboygan, Wisconsin.",
      "Struggling to swallow a live bat.",
      "Taking off my glasses and becoming beautiful.",
      "The tiny man who lives inside the ATM and hands out all the money.",
      "The tiny man who only eats coffee beans and diarrheas into my thermos every morning.",
      "Using electric eels to solve the world's energy crisis.",
      "Why, a hot air balloon of course!",
      "You there! French boy!"
    ]
  }
];

export const DEFAULT_ENABLED_PACK_IDS = [
  "retail-mini-pack",
  "90s-nostalgia-pack",
  "geek-pack",
  "sci-fi-pack",
  "movie-night-box",
  "fantasy-pack",
  "world-wide-web-pack",
  "science-pack",
  "food-pack",
  "pussy-pack",
  "period-pack",
  "weed-pack",
  "college-pack",
  "saves-america",
  "dad-pack-dvd-cover-s",
  "pride-pack",
  "ass-pack",
  "2000s-nostalgia-pack",
  "hidden-gems-bundle-a-few-new-cards-we-crammed-into-t",
  "nerd-bundle-a-few-more-cards-for-you-nerds-target-ex",
  "pop-culture-bundle-a-few-extra-cards-about-pop-cultu",
  "human-pack",
  "picture-card-pack-1",
  "picture-card-pack-2",
  "climate-catastrophe-pack",
  "scary-pack",
  "picture-pack-3",
  "clam-pack",
  "cultural-wars-pack",
  "2012-holiday-pack",
  "2013-holiday-pack",
  "2014-holiday-pack",
  "jew-pack-chosen-people-pack",
  "seasons-greetings-pack",
  "pax-2012-oops-kit",
  "pax-east-2013-promo-pack-a",
  "pax-east-2013-promo-pack-b",
  "pax-east-2013-promo-pack-c",
  "pax-prime-2013",
  "pax-east-2014",
  "pax-east-2014-panel-cards",
  "pax-prime-2014-panel-cards",
  "pax-prime-2014-custom-printed-cards",
  "pax-prime-2015-food-pack-c-cherry",
  "gen-con-2018-midterm-election-pack",
  "jack-white-show-pack",
  "reject-pack",
  "reject-pack-2",
  "house-of-cards-pack",
  "tabletop-pack",
  "trump-bug-out-bag-post-trump-pack",
  "fascism-pack",
  "mass-effect-pack",
  "retail-product-pack",
  "vote-for-hillary-pack",
  "vote-for-trump-pack",
  "desert-bus-for-hope-pack",
  "saves-america-2",
  "theatre-pack-cats-musical-pack",
  "reject-pack-3"
];

export function getEnabledCardPools(enabledPackIds: string[]) {
  const enabled = CAMPFIRE_CARD_PACKS.filter((pack) => enabledPackIds.includes(pack.id));
  const fallback = CAMPFIRE_CARD_PACKS.filter((pack) => DEFAULT_ENABLED_PACK_IDS.includes(pack.id));
  const packs = enabled.length ? enabled : fallback;

  return {
    prompts: packs.flatMap((pack) => pack.prompts.map((text) => ({ packId: pack.id, text }))),
    answers: packs.flatMap((pack) => pack.answers.map((text) => ({ packId: pack.id, text })))
  };
}
